<u>livymorph\.irrcircumfero\_presapl1</u><u>lexent\.n8171</u>circumferens<masc><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl2</u><u>lexent\.n8171</u>circumferentis<masc><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl3</u><u>lexent\.n8171</u>circumferenti<masc><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl4</u><u>lexent\.n8171</u>circumferentem<masc><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl5</u><u>lexent\.n8171</u>circumferente<masc><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl5b</u><u>lexent\.n8171</u>circumferenti<masc><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl6</u><u>lexent\.n8171</u>circumferens<masc><voc><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl7</u><u>lexent\.n8171</u>circumferentes<masc><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl8</u><u>lexent\.n8171</u>circumferentium<masc><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl9</u><u>lexent\.n8171</u>circumferentibus<masc><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl10</u><u>lexent\.n8171</u>circumferentes<masc><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl10b</u><u>lexent\.n8171</u>circumferentis<masc><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl11</u><u>lexent\.n8171</u>circumferentibus<masc><abl><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl12</u><u>lexent\.n8171</u>circumferentes<masc><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl13</u><u>lexent\.n8171</u>circumferens<fem><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl14</u><u>lexent\.n8171</u>circumferentis<fem><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl15</u><u>lexent\.n8171</u>circumferenti<fem><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl16</u><u>lexent\.n8171</u>circumferentem<fem><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl17</u><u>lexent\.n8171</u>circumferente<fem><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl17b</u><u>lexent\.n8171</u>circumferenti<fem><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl18</u><u>lexent\.n8171</u>circumferens<fem><voc><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl19</u><u>lexent\.n8171</u>circumferentes<fem><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl20</u><u>lexent\.n8171</u>circumferentium<fem><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl21</u><u>lexent\.n8171</u>circumferentibus<fem><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl22</u><u>lexent\.n8171</u>circumferentes<fem><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl22b</u><u>lexent\.n8171</u>circumferentis<fem><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl23</u><u>lexent\.n8171</u>circumferentibus<fem><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl24</u><u>lexent\.n8171</u>circumferentes<fem><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl25</u><u>lexent\.n8171</u>circumferens<neut><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl26</u><u>lexent\.n8171</u>circumferentis<neut><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl27</u><u>lexent\.n8171</u>circumferenti<neut><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl28</u><u>lexent\.n8171</u>circumferens<neut><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl29</u><u>lexent\.n8171</u>circumferente<neut><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl29b</u><u>lexent\.n8171</u>circumferenti<neut><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl30</u><u>lexent\.n8171</u>circumferens<neut><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl31</u><u>lexent\.n8171</u>circumferentia<neut><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl32</u><u>lexent\.n8171</u>circumferentium<neut><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl33</u><u>lexent\.n8171</u>circumferentibus<neut><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl34</u><u>lexent\.n8171</u>circumferentia<neut><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl35</u><u>lexent\.n8171</u>circumferentibus<neut><abl><pl><pres><act><irregptcpl>
<u>livymorph\.irrcircumfero\_presapl36</u><u>lexent\.n8171</u>circumferentia<neut><voc><pl><pres><act><irregptcpl>

<u>livymorph\.irrconfero\_presapl1</u><u>lexent\.n10088</u>conferens<masc><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl2</u><u>lexent\.n10088</u>conferentis<masc><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl3</u><u>lexent\.n10088</u>conferenti<masc><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl4</u><u>lexent\.n10088</u>conferentem<masc><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl5</u><u>lexent\.n10088</u>conferente<masc><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl5b</u><u>lexent\.n10088</u>conferenti<masc><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl6</u><u>lexent\.n10088</u>conferens<masc><voc><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl7</u><u>lexent\.n10088</u>conferentes<masc><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl8</u><u>lexent\.n10088</u>conferentium<masc><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl9</u><u>lexent\.n10088</u>conferentibus<masc><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl10</u><u>lexent\.n10088</u>conferentes<masc><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl10b</u><u>lexent\.n10088</u>conferentis<masc><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl11</u><u>lexent\.n10088</u>conferentibus<masc><abl><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl12</u><u>lexent\.n10088</u>conferentes<masc><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl13</u><u>lexent\.n10088</u>conferens<fem><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl14</u><u>lexent\.n10088</u>conferentis<fem><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl15</u><u>lexent\.n10088</u>conferenti<fem><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl16</u><u>lexent\.n10088</u>conferentem<fem><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl17</u><u>lexent\.n10088</u>conferente<fem><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl17b</u><u>lexent\.n10088</u>conferenti<fem><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl18</u><u>lexent\.n10088</u>conferens<fem><voc><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl19</u><u>lexent\.n10088</u>conferentes<fem><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl20</u><u>lexent\.n10088</u>conferentium<fem><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl21</u><u>lexent\.n10088</u>conferentibus<fem><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl22</u><u>lexent\.n10088</u>conferentes<fem><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl22b</u><u>lexent\.n10088</u>conferentis<fem><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl23</u><u>lexent\.n10088</u>conferentibus<fem><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl24</u><u>lexent\.n10088</u>conferentes<fem><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl25</u><u>lexent\.n10088</u>conferens<neut><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl26</u><u>lexent\.n10088</u>conferentis<neut><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl27</u><u>lexent\.n10088</u>conferenti<neut><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl28</u><u>lexent\.n10088</u>conferens<neut><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl29</u><u>lexent\.n10088</u>conferente<neut><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl29b</u><u>lexent\.n10088</u>conferenti<neut><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl30</u><u>lexent\.n10088</u>conferens<neut><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl31</u><u>lexent\.n10088</u>conferentia<neut><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl32</u><u>lexent\.n10088</u>conferentium<neut><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl33</u><u>lexent\.n10088</u>conferentibus<neut><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl34</u><u>lexent\.n10088</u>conferentia<neut><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl35</u><u>lexent\.n10088</u>conferentibus<neut><abl><pl><pres><act><irregptcpl>
<u>livymorph\.irrconfero\_presapl36</u><u>lexent\.n10088</u>conferentia<neut><voc><pl><pres><act><irregptcpl>

<u>livymorph\.irreo\_presapl1</u><u>lexent\.n15868</u>euns<masc><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl2</u><u>lexent\.n15868</u>euntis<masc><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl3</u><u>lexent\.n15868</u>eunti<masc><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl4</u><u>lexent\.n15868</u>euntem<masc><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl5</u><u>lexent\.n15868</u>eunte<masc><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl5b</u><u>lexent\.n15868</u>eunti<masc><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl6</u><u>lexent\.n15868</u>euns<masc><voc><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl7</u><u>lexent\.n15868</u>euntes<masc><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl8</u><u>lexent\.n15868</u>euntium<masc><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl9</u><u>lexent\.n15868</u>euntibus<masc><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl10</u><u>lexent\.n15868</u>euntes<masc><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl10b</u><u>lexent\.n15868</u>euntis<masc><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl11</u><u>lexent\.n15868</u>euntibus<masc><abl><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl12</u><u>lexent\.n15868</u>euntes<masc><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl13</u><u>lexent\.n15868</u>euns<fem><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl14</u><u>lexent\.n15868</u>euntis<fem><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl15</u><u>lexent\.n15868</u>eunti<fem><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl16</u><u>lexent\.n15868</u>euntem<fem><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl17</u><u>lexent\.n15868</u>eunte<fem><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl17b</u><u>lexent\.n15868</u>eunti<fem><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl18</u><u>lexent\.n15868</u>euns<fem><voc><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl19</u><u>lexent\.n15868</u>euntes<fem><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl20</u><u>lexent\.n15868</u>euntium<fem><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl21</u><u>lexent\.n15868</u>euntibus<fem><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl22</u><u>lexent\.n15868</u>euntes<fem><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl22b</u><u>lexent\.n15868</u>euntis<fem><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl23</u><u>lexent\.n15868</u>euntibus<fem><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl24</u><u>lexent\.n15868</u>euntes<fem><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl25</u><u>lexent\.n15868</u>euns<neut><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl26</u><u>lexent\.n15868</u>euntis<neut><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl27</u><u>lexent\.n15868</u>eunti<neut><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl28</u><u>lexent\.n15868</u>euns<neut><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl29</u><u>lexent\.n15868</u>eunte<neut><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl29b</u><u>lexent\.n15868</u>eunti<neut><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl30</u><u>lexent\.n15868</u>euns<neut><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl31</u><u>lexent\.n15868</u>euntia<neut><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl32</u><u>lexent\.n15868</u>euntium<neut><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl33</u><u>lexent\.n15868</u>euntibus<neut><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl34</u><u>lexent\.n15868</u>euntia<neut><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl35</u><u>lexent\.n15868</u>euntibus<neut><abl><pl><pres><act><irregptcpl>
<u>livymorph\.irreo\_presapl36</u><u>lexent\.n15868</u>euntia<neut><voc><pl><pres><act><irregptcpl>

<u>livymorph\.irrexeo\_presapl1</u><u>lexent\.n16804</u>exeuns<masc><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl2</u><u>lexent\.n16804</u>exeuntis<masc><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl3</u><u>lexent\.n16804</u>exeunti<masc><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl4</u><u>lexent\.n16804</u>exeuntem<masc><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl5</u><u>lexent\.n16804</u>exeunte<masc><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl5b</u><u>lexent\.n16804</u>exeunti<masc><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl6</u><u>lexent\.n16804</u>exeuns<masc><voc><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl7</u><u>lexent\.n16804</u>exeuntes<masc><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl8</u><u>lexent\.n16804</u>exeuntium<masc><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl9</u><u>lexent\.n16804</u>exeuntibus<masc><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl10</u><u>lexent\.n16804</u>exeuntes<masc><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl10b</u><u>lexent\.n16804</u>exeuntis<masc><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl11</u><u>lexent\.n16804</u>exeuntibus<masc><abl><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl12</u><u>lexent\.n16804</u>exeuntes<masc><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl13</u><u>lexent\.n16804</u>exeuns<fem><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl14</u><u>lexent\.n16804</u>exeuntis<fem><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl15</u><u>lexent\.n16804</u>exeunti<fem><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl16</u><u>lexent\.n16804</u>exeuntem<fem><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl17</u><u>lexent\.n16804</u>exeunte<fem><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl17b</u><u>lexent\.n16804</u>exeunti<fem><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl18</u><u>lexent\.n16804</u>exeuns<fem><voc><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl19</u><u>lexent\.n16804</u>exeuntes<fem><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl20</u><u>lexent\.n16804</u>exeuntium<fem><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl21</u><u>lexent\.n16804</u>exeuntibus<fem><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl22</u><u>lexent\.n16804</u>exeuntes<fem><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl22b</u><u>lexent\.n16804</u>exeuntis<fem><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl23</u><u>lexent\.n16804</u>exeuntibus<fem><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl24</u><u>lexent\.n16804</u>exeuntes<fem><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl25</u><u>lexent\.n16804</u>exeuns<neut><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl26</u><u>lexent\.n16804</u>exeuntis<neut><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl27</u><u>lexent\.n16804</u>exeunti<neut><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl28</u><u>lexent\.n16804</u>exeuns<neut><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl29</u><u>lexent\.n16804</u>exeunte<neut><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl29b</u><u>lexent\.n16804</u>exeunti<neut><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl30</u><u>lexent\.n16804</u>exeuns<neut><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl31</u><u>lexent\.n16804</u>exeuntia<neut><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl32</u><u>lexent\.n16804</u>exeuntium<neut><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl33</u><u>lexent\.n16804</u>exeuntibus<neut><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl34</u><u>lexent\.n16804</u>exeuntia<neut><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl35</u><u>lexent\.n16804</u>exeuntibus<neut><abl><pl><pres><act><irregptcpl>
<u>livymorph\.irrexeo\_presapl36</u><u>lexent\.n16804</u>exeuntia<neut><voc><pl><pres><act><irregptcpl>

<u>livymorph\.irrfero\_presapl1</u><u>lexent\.n17964</u>ferens<masc><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl2</u><u>lexent\.n17964</u>ferentis<masc><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl3</u><u>lexent\.n17964</u>ferenti<masc><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl4</u><u>lexent\.n17964</u>ferentem<masc><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl5</u><u>lexent\.n17964</u>ferente<masc><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl5b</u><u>lexent\.n17964</u>ferenti<masc><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl6</u><u>lexent\.n17964</u>ferens<masc><voc><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl7</u><u>lexent\.n17964</u>ferentes<masc><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl8</u><u>lexent\.n17964</u>ferentium<masc><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl9</u><u>lexent\.n17964</u>ferentibus<masc><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl10</u><u>lexent\.n17964</u>ferentes<masc><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl10b</u><u>lexent\.n17964</u>ferentis<masc><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl11</u><u>lexent\.n17964</u>ferentibus<masc><abl><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl12</u><u>lexent\.n17964</u>ferentes<masc><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl13</u><u>lexent\.n17964</u>ferens<fem><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl14</u><u>lexent\.n17964</u>ferentis<fem><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl15</u><u>lexent\.n17964</u>ferenti<fem><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl16</u><u>lexent\.n17964</u>ferentem<fem><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl17</u><u>lexent\.n17964</u>ferente<fem><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl17b</u><u>lexent\.n17964</u>ferenti<fem><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl18</u><u>lexent\.n17964</u>ferens<fem><voc><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl19</u><u>lexent\.n17964</u>ferentes<fem><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl20</u><u>lexent\.n17964</u>ferentium<fem><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl21</u><u>lexent\.n17964</u>ferentibus<fem><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl22</u><u>lexent\.n17964</u>ferentes<fem><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl22b</u><u>lexent\.n17964</u>ferentis<fem><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl23</u><u>lexent\.n17964</u>ferentibus<fem><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl24</u><u>lexent\.n17964</u>ferentes<fem><voc><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl25</u><u>lexent\.n17964</u>ferens<neut><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl26</u><u>lexent\.n17964</u>ferentis<neut><gen><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl27</u><u>lexent\.n17964</u>ferenti<neut><dat><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl28</u><u>lexent\.n17964</u>ferens<neut><acc><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl29</u><u>lexent\.n17964</u>ferente<neut><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl29b</u><u>lexent\.n17964</u>ferenti<neut><abl><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl30</u><u>lexent\.n17964</u>ferens<neut><nom><sg><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl31</u><u>lexent\.n17964</u>ferentia<neut><nom><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl32</u><u>lexent\.n17964</u>ferentium<neut><gen><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl33</u><u>lexent\.n17964</u>ferentibus<neut><dat><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl34</u><u>lexent\.n17964</u>ferentia<neut><acc><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl35</u><u>lexent\.n17964</u>ferentibus<neut><abl><pl><pres><act><irregptcpl>
<u>livymorph\.irrfero\_presapl36</u><u>lexent\.n17964</u>ferentia<neut><voc><pl><pres><act><irregptcpl>
