<u>livymorph\.irralter1</u><u>lexent\.n2015</u>alter<masc><nom><sg><pos><irregadj>
<u>livymorph\.irralter2</u><u>lexent\.n2015</u>alterius<masc><gen><sg><pos><irregadj>
<u>livymorph\.irralter3</u><u>lexent\.n2015</u>alteri<masc><dat><sg><pos><irregadj>
<u>livymorph\.irralter4</u><u>lexent\.n2015</u>alterum<masc><acc><sg><pos><irregadj>
<u>livymorph\.irralter5</u><u>lexent\.n2015</u>altero<masc><abl><sg><pos><irregadj>
<u>livymorph\.irralter6</u><u>lexent\.n2015</u>alteri<masc><nom><pl><pos><irregadj>
<u>livymorph\.irralter7</u><u>lexent\.n2015</u>alterorum<masc><gen><pl><pos><irregadj>
<u>livymorph\.irralter8</u><u>lexent\.n2015</u>alteris<masc><dat><pl><pos><irregadj>
<u>livymorph\.irralter9</u><u>lexent\.n2015</u>alteros<masc><acc><pl><pos><irregadj>
<u>livymorph\.irralter10</u><u>lexent\.n2015</u>alteris<masc><abl><pl><pos><irregadj>
<u>livymorph\.irralter11</u><u>lexent\.n2015</u>alter<masc><voc><sg><pos><irregadj>
<u>livymorph\.irralter12</u><u>lexent\.n2015</u>alteri<masc><voc><pl><pos><irregadj>
<u>livymorph\.irralter13</u><u>lexent\.n2015</u>altera<fem><nom><sg><pos><irregadj>
<u>livymorph\.irralter14</u><u>lexent\.n2015</u>alterius<fem><gen><sg><pos><irregadj>
<u>livymorph\.irralter15</u><u>lexent\.n2015</u>alteri<fem><dat><sg><pos><irregadj>
<u>livymorph\.irralter16</u><u>lexent\.n2015</u>alteram<fem><acc><sg><pos><irregadj>
<u>livymorph\.irralter17</u><u>lexent\.n2015</u>altera<fem><abl><sg><pos><irregadj>
<u>livymorph\.irralter18</u><u>lexent\.n2015</u>alterae<fem><nom><pl><pos><irregadj>
<u>livymorph\.irralter19</u><u>lexent\.n2015</u>alterarum<fem><gen><pl><pos><irregadj>
<u>livymorph\.irralter20</u><u>lexent\.n2015</u>alteris<fem><dat><pl><pos><irregadj>
<u>livymorph\.irralter21</u><u>lexent\.n2015</u>alteras<fem><acc><pl><pos><irregadj>
<u>livymorph\.irralter22</u><u>lexent\.n2015</u>alteris<fem><abl><pl><pos><irregadj>
<u>livymorph\.irralter23</u><u>lexent\.n2015</u>altera<fem><voc><sg><pos><irregadj>
<u>livymorph\.irralter24</u><u>lexent\.n2015</u>alterae<fem><voc><pl><pos><irregadj>
<u>livymorph\.irralter25</u><u>lexent\.n2015</u>alterum<neut><nom><sg><pos><irregadj>
<u>livymorph\.irralter26</u><u>lexent\.n2015</u>alterius<neut><gen><sg><pos><irregadj>
<u>livymorph\.irralter27</u><u>lexent\.n2015</u>alteri<neut><dat><sg><pos><irregadj>
<u>livymorph\.irralter28</u><u>lexent\.n2015</u>alterum<neut><acc><sg><pos><irregadj>
<u>livymorph\.irralter29</u><u>lexent\.n2015</u>altero<neut><abl><sg><pos><irregadj>
<u>livymorph\.irralter30</u><u>lexent\.n2015</u>altera<neut><nom><pl><pos><irregadj>
<u>livymorph\.irralter31</u><u>lexent\.n2015</u>alterorum<neut><gen><pl><pos><irregadj>
<u>livymorph\.irralter32</u><u>lexent\.n2015</u>alteris<neut><dat><pl><pos><irregadj>
<u>livymorph\.irralter33</u><u>lexent\.n2015</u>altera<neut><acc><pl><pos><irregadj>
<u>livymorph\.irralter34</u><u>lexent\.n2015</u>alteris<neut><abl><pl><pos><irregadj>
<u>livymorph\.irralter35</u><u>lexent\.n2015</u>alterum<neut><voc><sg><pos><irregadj>
<u>livymorph\.irralter36</u><u>lexent\.n2015</u>altera<neut><voc><pl><pos><irregadj>

<u>livymorph\.irrambo1</u><u>lexent\.n2176</u>ambo<masc><nom><pl><pos><irregadj>
<u>livymorph\.irrambo2</u><u>lexent\.n2176</u>ambo<masc><voc><pl><pos><irregadj>
<u>livymorph\.irrambo3</u><u>lexent\.n2176</u>ambo<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrambo3b</u><u>lexent\.n2176</u>ambos<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrambo4</u><u>lexent\.n2176</u>ambo<neut><nom><pl><pos><irregadj>
<u>livymorph\.irrambo5</u><u>lexent\.n2176</u>ambo<neut><voc><pl><pos><irregadj>
<u>livymorph\.irrambo6</u><u>lexent\.n2176</u>ambo<neut><acc><pl><pos><irregadj>
<u>livymorph\.irrambo7</u><u>lexent\.n2176</u>ambae<fem><nom><pl><pos><irregadj>
<u>livymorph\.irrambo8</u><u>lexent\.n2176</u>ambae<fem><voc><pl><pos><irregadj>
<u>livymorph\.irrambo9</u><u>lexent\.n2176</u>ambas<fem><acc><pl><pos><irregadj>
<u>livymorph\.irrambo10</u><u>lexent\.n2176</u>unis<masc><abl><pl><pos><irregadj>

<u>livymorph\.irrbonus1</u><u>lexent\.n2015</u>bonus<masc><nom><sg><pos><irregadj>
<u>livymorph\.irrbonus2</u><u>lexent\.n2015</u>boni<masc><gen><sg><pos><irregadj>
<u>livymorph\.irrbonus3</u><u>lexent\.n2015</u>bono<masc><dat><sg><pos><irregadj>
<u>livymorph\.irrbonus4</u><u>lexent\.n2015</u>bonum<masc><acc><sg><pos><irregadj>
<u>livymorph\.irrbonus5</u><u>lexent\.n2015</u>bono<masc><abl><sg><pos><irregadj>
<u>livymorph\.irrbonus6</u><u>lexent\.n2015</u>boni<masc><nom><pl><pos><irregadj>
<u>livymorph\.irrbonus7</u><u>lexent\.n2015</u>bonorum<masc><gen><pl><pos><irregadj>
<u>livymorph\.irrbonus8</u><u>lexent\.n2015</u>bonis<masc><dat><pl><pos><irregadj>
<u>livymorph\.irrbonus9</u><u>lexent\.n2015</u>bonos<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrbonus10</u><u>lexent\.n2015</u>bonis<masc><abl><pl><pos><irregadj>
<u>livymorph\.irrbonus11</u><u>lexent\.n2015</u>bone<masc><voc><sg><pos><irregadj>
<u>livymorph\.irrbonus12</u><u>lexent\.n2015</u>boni<masc><voc><pl><pos><irregadj>
<u>livymorph\.irrbonus13</u><u>lexent\.n2015</u>bona<fem><nom><sg><pos><irregadj>
<u>livymorph\.irrbonus14</u><u>lexent\.n2015</u>bonae<fem><gen><sg><pos><irregadj>
<u>livymorph\.irrbonus15</u><u>lexent\.n2015</u>bonae<fem><dat><sg><pos><irregadj>
<u>livymorph\.irrbonus16</u><u>lexent\.n2015</u>bonam<fem><acc><sg><pos><irregadj>
<u>livymorph\.irrbonus17</u><u>lexent\.n2015</u>bona<fem><abl><sg><pos><irregadj>
<u>livymorph\.irrbonus18</u><u>lexent\.n2015</u>bonae<fem><nom><pl><pos><irregadj>
<u>livymorph\.irrbonus19</u><u>lexent\.n2015</u>bonarum<fem><gen><pl><pos><irregadj>
<u>livymorph\.irrbonus20</u><u>lexent\.n2015</u>bonis<fem><dat><pl><pos><irregadj>
<u>livymorph\.irrbonus21</u><u>lexent\.n2015</u>bonas<fem><acc><pl><pos><irregadj>
<u>livymorph\.irrbonus22</u><u>lexent\.n2015</u>bonis<fem><abl><pl><pos><irregadj>
<u>livymorph\.irrbonus23</u><u>lexent\.n2015</u>bona<fem><voc><sg><pos><irregadj>
<u>livymorph\.irrbonus24</u><u>lexent\.n2015</u>bonae<fem><voc><pl><pos><irregadj>
<u>livymorph\.irrbonus25</u><u>lexent\.n2015</u>bonum<neut><nom><sg><pos><irregadj>
<u>livymorph\.irrbonus26</u><u>lexent\.n2015</u>boni<neut><gen><sg><pos><irregadj>
<u>livymorph\.irrbonus27</u><u>lexent\.n2015</u>bono<neut><dat><sg><pos><irregadj>
<u>livymorph\.irrbonus28</u><u>lexent\.n2015</u>bonum<neut><acc><sg><pos><irregadj>
<u>livymorph\.irrbonus29</u><u>lexent\.n2015</u>bono<neut><abl><sg><pos><irregadj>
<u>livymorph\.irrbonus30</u><u>lexent\.n2015</u>bona<neut><nom><pl><pos><irregadj>
<u>livymorph\.irrbonus31</u><u>lexent\.n2015</u>bonorum<neut><gen><pl><pos><irregadj>
<u>livymorph\.irrbonus32</u><u>lexent\.n2015</u>bonis<neut><dat><pl><pos><irregadj>
<u>livymorph\.irrbonus33</u><u>lexent\.n2015</u>bona<neut><acc><pl><pos><irregadj>
<u>livymorph\.irrbonus34</u><u>lexent\.n2015</u>bonis<neut><abl><pl><pos><irregadj>
<u>livymorph\.irrbonus35</u><u>lexent\.n2015</u>bonum<neut><voc><sg><pos><irregadj>
<u>livymorph\.irrbonus36</u><u>lexent\.n2015</u>bona<neut><voc><pl><pos><irregadj>
<u>livymorph\.irrbonus37</u><u>lexent\.n2015</u>melior<masc><nom><sg><comp><irregadj>
<u>livymorph\.irrbonus38</u><u>lexent\.n2015</u>melioris<masc><gen><sg><comp><irregadj>
<u>livymorph\.irrbonus39</u><u>lexent\.n2015</u>meliori<masc><dat><sg><comp><irregadj>
<u>livymorph\.irrbonus40</u><u>lexent\.n2015</u>meliorem<masc><acc><sg><comp><irregadj>
<u>livymorph\.irrbonus41</u><u>lexent\.n2015</u>meliore<masc><abl><sg><comp><irregadj>
<u>livymorph\.irrbonus41b</u><u>lexent\.n2015</u>meliori<masc><abl><sg><comp><irregadj>
<u>livymorph\.irrbonus42</u><u>lexent\.n2015</u>meliores<masc><nom><pl><comp><irregadj>
<u>livymorph\.irrbonus43</u><u>lexent\.n2015</u>meliorum<masc><gen><pl><comp><irregadj>
<u>livymorph\.irrbonus44</u><u>lexent\.n2015</u>melioribus<masc><dat><pl><comp><irregadj>
<u>livymorph\.irrbonus45</u><u>lexent\.n2015</u>meliores<masc><acc><pl><comp><irregadj>
<u>livymorph\.irrbonus45b</u><u>lexent\.n2015</u>melioris<masc><acc><pl><comp><irregadj>
<u>livymorph\.irrbonus46</u><u>lexent\.n2015</u>melioribus<masc><abl><pl><comp><irregadj>
<u>livymorph\.irrbonus47</u><u>lexent\.n2015</u>melior<masc><voc><sg><comp><irregadj>
<u>livymorph\.irrbonus48</u><u>lexent\.n2015</u>meliores<masc><voc><pl><comp><irregadj>
<u>livymorph\.irrbonus49</u><u>lexent\.n2015</u>melior<fem><nom><sg><comp><irregadj>
<u>livymorph\.irrbonus50</u><u>lexent\.n2015</u>melioris<fem><gen><sg><comp><irregadj>
<u>livymorph\.irrbonus51</u><u>lexent\.n2015</u>meliori<fem><dat><sg><comp><irregadj>
<u>livymorph\.irrbonus52</u><u>lexent\.n2015</u>meliorem<fem><acc><sg><comp><irregadj>
<u>livymorph\.irrbonus53</u><u>lexent\.n2015</u>meliore<fem><abl><sg><comp><irregadj>
<u>livymorph\.irrbonus53b</u><u>lexent\.n2015</u>meliori<fem><abl><sg><comp><irregadj>
<u>livymorph\.irrbonus54</u><u>lexent\.n2015</u>meliores<fem><nom><pl><comp><irregadj>
<u>livymorph\.irrbonus55</u><u>lexent\.n2015</u>meliorum<fem><gen><pl><comp><irregadj>
<u>livymorph\.irrbonus56</u><u>lexent\.n2015</u>melioribus<fem><dat><pl><comp><irregadj>
<u>livymorph\.irrbonus57</u><u>lexent\.n2015</u>meliores<fem><acc><pl><comp><irregadj>
<u>livymorph\.irrbonus57b</u><u>lexent\.n2015</u>melioris<fem><acc><pl><comp><irregadj>
<u>livymorph\.irrbonus58</u><u>lexent\.n2015</u>melioribus<fem><abl><pl><comp><irregadj>
<u>livymorph\.irrbonus59</u><u>lexent\.n2015</u>melior<fem><voc><sg><comp><irregadj>
<u>livymorph\.irrbonus60</u><u>lexent\.n2015</u>meliores<fem><voc><pl><comp><irregadj>
<u>livymorph\.irrbonus61</u><u>lexent\.n2015</u>melius<neut><nom><sg><comp><irregadj>
<u>livymorph\.irrbonus62</u><u>lexent\.n2015</u>melioris<neut><gen><sg><comp><irregadj>
<u>livymorph\.irrbonus63</u><u>lexent\.n2015</u>meliori<neut><dat><sg><comp><irregadj>
<u>livymorph\.irrbonus64</u><u>lexent\.n2015</u>melius<neut><acc><sg><comp><irregadj>
<u>livymorph\.irrbonus65</u><u>lexent\.n2015</u>meliore<neut><abl><sg><comp><irregadj>
<u>livymorph\.irrbonus65b</u><u>lexent\.n2015</u>meliori<neut><abl><sg><comp><irregadj>
<u>livymorph\.irrbonus66</u><u>lexent\.n2015</u>meliora<neut><nom><pl><comp><irregadj>
<u>livymorph\.irrbonus67</u><u>lexent\.n2015</u>meliorum<neut><gen><pl><comp><irregadj>
<u>livymorph\.irrbonus68</u><u>lexent\.n2015</u>melioribus<neut><dat><pl><comp><irregadj>
<u>livymorph\.irrbonus69</u><u>lexent\.n2015</u>meliora<neut><acc><pl><comp><irregadj>
<u>livymorph\.irrbonus70</u><u>lexent\.n2015</u>melioribus<neut><abl><pl><comp><irregadj>
<u>livymorph\.irrbonus71</u><u>lexent\.n2015</u>melius<neut><voc><sg><comp><irregadj>
<u>livymorph\.irrbonus72</u><u>lexent\.n2015</u>meliora<neut><voc><pl><comp><irregadj>
<u>livymorph\.irrbonus73</u><u>lexent\.n2015</u>optimus<masc><nom><sg><superl><irregadj>
<u>livymorph\.irrbonus74</u><u>lexent\.n2015</u>optimi<masc><gen><sg><superl><irregadj>
<u>livymorph\.irrbonus75</u><u>lexent\.n2015</u>optimo<masc><dat><sg><superl><irregadj>
<u>livymorph\.irrbonus76</u><u>lexent\.n2015</u>optimum<masc><acc><sg><superl><irregadj>
<u>livymorph\.irrbonus77</u><u>lexent\.n2015</u>optimo<masc><abl><sg><superl><irregadj>
<u>livymorph\.irrbonus78</u><u>lexent\.n2015</u>optimi<masc><nom><pl><superl><irregadj>
<u>livymorph\.irrbonus79</u><u>lexent\.n2015</u>optimorum<masc><gen><pl><superl><irregadj>
<u>livymorph\.irrbonus80</u><u>lexent\.n2015</u>optimis<masc><dat><pl><superl><irregadj>
<u>livymorph\.irrbonus81</u><u>lexent\.n2015</u>optimos<masc><acc><pl><superl><irregadj>
<u>livymorph\.irrbonus82</u><u>lexent\.n2015</u>optimis<masc><abl><pl><superl><irregadj>
<u>livymorph\.irrbonus83</u><u>lexent\.n2015</u>optime<masc><voc><sg><superl><irregadj>
<u>livymorph\.irrbonus84</u><u>lexent\.n2015</u>optimi<masc><voc><pl><superl><irregadj>
<u>livymorph\.irrbonus85</u><u>lexent\.n2015</u>optima<fem><nom><sg><superl><irregadj>
<u>livymorph\.irrbonus86</u><u>lexent\.n2015</u>optimae<fem><gen><sg><superl><irregadj>
<u>livymorph\.irrbonus87</u><u>lexent\.n2015</u>optimae<fem><dat><sg><superl><irregadj>
<u>livymorph\.irrbonus88</u><u>lexent\.n2015</u>optimam<fem><acc><sg><superl><irregadj>
<u>livymorph\.irrbonus89</u><u>lexent\.n2015</u>optima<fem><abl><sg><superl><irregadj>
<u>livymorph\.irrbonus90</u><u>lexent\.n2015</u>optimae<fem><nom><pl><superl><irregadj>
<u>livymorph\.irrbonus91</u><u>lexent\.n2015</u>optimarum<fem><gen><pl><superl><irregadj>
<u>livymorph\.irrbonus92</u><u>lexent\.n2015</u>optimis<fem><dat><pl><superl><irregadj>
<u>livymorph\.irrbonus93</u><u>lexent\.n2015</u>optimas<fem><acc><pl><superl><irregadj>
<u>livymorph\.irrbonus94</u><u>lexent\.n2015</u>optimis<fem><abl><pl><superl><irregadj>
<u>livymorph\.irrbonus95</u><u>lexent\.n2015</u>optima<fem><voc><sg><superl><irregadj>
<u>livymorph\.irrbonus96</u><u>lexent\.n2015</u>optimae<fem><voc><pl><superl><irregadj>
<u>livymorph\.irrbonus97</u><u>lexent\.n2015</u>optimum<neut><nom><sg><superl><irregadj>
<u>livymorph\.irrbonus98</u><u>lexent\.n2015</u>optimi<neut><gen><sg><superl><irregadj>
<u>livymorph\.irrbonus99</u><u>lexent\.n2015</u>optimo<neut><dat><sg><superl><irregadj>
<u>livymorph\.irrbonus100</u><u>lexent\.n2015</u>optimum<neut><acc><sg><superl><irregadj>
<u>livymorph\.irrbonus101</u><u>lexent\.n2015</u>optimo<neut><abl><sg><superl><irregadj>
<u>livymorph\.irrbonus102</u><u>lexent\.n2015</u>optima<neut><nom><pl><superl><irregadj>
<u>livymorph\.irrbonus103</u><u>lexent\.n2015</u>optimorum<neut><gen><pl><superl><irregadj>
<u>livymorph\.irrbonus104</u><u>lexent\.n2015</u>optimis<neut><dat><pl><superl><irregadj>
<u>livymorph\.irrbonus105</u><u>lexent\.n2015</u>optima<neut><acc><pl><superl><irregadj>
<u>livymorph\.irrbonus106</u><u>lexent\.n2015</u>optimis<neut><abl><pl><superl><irregadj>
<u>livymorph\.irrbonus107</u><u>lexent\.n2015</u>optimum<neut><voc><sg><superl><irregadj>
<u>livymorph\.irrbonus108</u><u>lexent\.n2015</u>optima<neut><voc><pl><superl><irregadj>

<u>livymorph\.irrduo1</u><u>lexent\.n14914</u>duo<masc><nom><pl><pos><irregadj>
<u>livymorph\.irrduo2</u><u>lexent\.n14914</u>duorum<masc><gen><pl><pos><irregadj>
<u>livymorph\.irrduo3</u><u>lexent\.n14914</u>duobus<masc><dat><pl><pos><irregadj>
<u>livymorph\.irrduo4</u><u>lexent\.n14914</u>duos<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrduo4b</u><u>lexent\.n14914</u>duos<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrduo5</u><u>lexent\.n14914</u>duobus<masc><abl><pl><pos><irregadj>
<u>livymorph\.irrduo6</u><u>lexent\.n14914</u>duo<masc><voc><pl><pos><irregadj>
<u>livymorph\.irrduo7</u><u>lexent\.n14914</u>duae<fem><nom><pl><pos><irregadj>
<u>livymorph\.irrduo8</u><u>lexent\.n14914</u>unarum<fem><gen><pl><pos><irregadj>
<u>livymorph\.irrduo9</u><u>lexent\.n14914</u>duabus<fem><dat><pl><pos><irregadj>
<u>livymorph\.irrduo10</u><u>lexent\.n14914</u>duas<fem><acc><pl><pos><irregadj>
<u>livymorph\.irrduo11</u><u>lexent\.n14914</u>duabus<fem><abl><pl><pos><irregadj>
<u>livymorph\.irrduo12</u><u>lexent\.n14914</u>duae<fem><voc><pl><pos><irregadj>
<u>livymorph\.irrduo13</u><u>lexent\.n14914</u>duo<neut><nom><pl><pos><irregadj>
<u>livymorph\.irrduo14</u><u>lexent\.n14914</u>unorum<neut><gen><pl><pos><irregadj>
<u>livymorph\.irrduo15</u><u>lexent\.n14914</u>duobus<neut><dat><pl><pos><irregadj>
<u>livymorph\.irrduo16</u><u>lexent\.n14914</u>duo<neut><acc><pl><pos><irregadj>
<u>livymorph\.irrduo17</u><u>lexent\.n14914</u>duobus<neut><abl><pl><pos><irregadj>
<u>livymorph\.irrduo18</u><u>lexent\.n14914</u>duo<neut><voc><pl><pos><irregadj>

<u>livymorph\.irrmagnus1</u><u>lexent\.n27649</u>magnus<masc><nom><sg><pos><irregadj>
<u>livymorph\.irrmagnus2</u><u>lexent\.n27649</u>magni<masc><gen><sg><pos><irregadj>
<u>livymorph\.irrmagnus3</u><u>lexent\.n27649</u>magno<masc><dat><sg><pos><irregadj>
<u>livymorph\.irrmagnus4</u><u>lexent\.n27649</u>magnum<masc><acc><sg><pos><irregadj>
<u>livymorph\.irrmagnus5</u><u>lexent\.n27649</u>magno<masc><abl><sg><pos><irregadj>
<u>livymorph\.irrmagnus6</u><u>lexent\.n27649</u>magni<masc><nom><pl><pos><irregadj>
<u>livymorph\.irrmagnus7</u><u>lexent\.n27649</u>magnorum<masc><gen><pl><pos><irregadj>
<u>livymorph\.irrmagnus8</u><u>lexent\.n27649</u>magnis<masc><dat><pl><pos><irregadj>
<u>livymorph\.irrmagnus9</u><u>lexent\.n27649</u>magnos<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrmagnus10</u><u>lexent\.n27649</u>magnis<masc><abl><pl><pos><irregadj>
<u>livymorph\.irrmagnus11</u><u>lexent\.n27649</u>magne<masc><voc><sg><pos><irregadj>
<u>livymorph\.irrmagnus12</u><u>lexent\.n27649</u>magni<masc><voc><pl><pos><irregadj>
<u>livymorph\.irrmagnus13</u><u>lexent\.n27649</u>magna<fem><nom><sg><pos><irregadj>
<u>livymorph\.irrmagnus14</u><u>lexent\.n27649</u>magnae<fem><gen><sg><pos><irregadj>
<u>livymorph\.irrmagnus15</u><u>lexent\.n27649</u>magnae<fem><dat><sg><pos><irregadj>
<u>livymorph\.irrmagnus16</u><u>lexent\.n27649</u>magnam<fem><acc><sg><pos><irregadj>
<u>livymorph\.irrmagnus17</u><u>lexent\.n27649</u>magna<fem><abl><sg><pos><irregadj>
<u>livymorph\.irrmagnus18</u><u>lexent\.n27649</u>magnae<fem><nom><pl><pos><irregadj>
<u>livymorph\.irrmagnus19</u><u>lexent\.n27649</u>magnarum<fem><gen><pl><pos><irregadj>
<u>livymorph\.irrmagnus20</u><u>lexent\.n27649</u>magnis<fem><dat><pl><pos><irregadj>
<u>livymorph\.irrmagnus21</u><u>lexent\.n27649</u>magnas<fem><acc><pl><pos><irregadj>
<u>livymorph\.irrmagnus22</u><u>lexent\.n27649</u>magnis<fem><abl><pl><pos><irregadj>
<u>livymorph\.irrmagnus23</u><u>lexent\.n27649</u>magna<fem><voc><sg><pos><irregadj>
<u>livymorph\.irrmagnus24</u><u>lexent\.n27649</u>magnae<fem><voc><pl><pos><irregadj>
<u>livymorph\.irrmagnus25</u><u>lexent\.n27649</u>magnum<neut><nom><sg><pos><irregadj>
<u>livymorph\.irrmagnus26</u><u>lexent\.n27649</u>magni<neut><gen><sg><pos><irregadj>
<u>livymorph\.irrmagnus27</u><u>lexent\.n27649</u>magno<neut><dat><sg><pos><irregadj>
<u>livymorph\.irrmagnus28</u><u>lexent\.n27649</u>magnum<neut><acc><sg><pos><irregadj>
<u>livymorph\.irrmagnus29</u><u>lexent\.n27649</u>magno<neut><abl><sg><pos><irregadj>
<u>livymorph\.irrmagnus30</u><u>lexent\.n27649</u>magna<neut><nom><pl><pos><irregadj>
<u>livymorph\.irrmagnus31</u><u>lexent\.n27649</u>magnorum<neut><gen><pl><pos><irregadj>
<u>livymorph\.irrmagnus32</u><u>lexent\.n27649</u>magnis<neut><dat><pl><pos><irregadj>
<u>livymorph\.irrmagnus33</u><u>lexent\.n27649</u>magna<neut><acc><pl><pos><irregadj>
<u>livymorph\.irrmagnus34</u><u>lexent\.n27649</u>magnis<neut><abl><pl><pos><irregadj>
<u>livymorph\.irrmagnus35</u><u>lexent\.n27649</u>magnum<neut><voc><sg><pos><irregadj>
<u>livymorph\.irrmagnus36</u><u>lexent\.n27649</u>magna<neut><voc><pl><pos><irregadj>
<u>livymorph\.irrmagnus37</u><u>lexent\.n27649</u>maior<masc><nom><sg><comp><irregadj>
<u>livymorph\.irrmagnus38</u><u>lexent\.n27649</u>maioris<masc><gen><sg><comp><irregadj>
<u>livymorph\.irrmagnus39</u><u>lexent\.n27649</u>maiori<masc><dat><sg><comp><irregadj>
<u>livymorph\.irrmagnus40</u><u>lexent\.n27649</u>maiorem<masc><acc><sg><comp><irregadj>
<u>livymorph\.irrmagnus41</u><u>lexent\.n27649</u>maiore<masc><abl><sg><comp><irregadj>
<u>livymorph\.irrmagnus41b</u><u>lexent\.n27649</u>maiori<masc><abl><sg><comp><irregadj>
<u>livymorph\.irrmagnus42</u><u>lexent\.n27649</u>maiores<masc><nom><pl><comp><irregadj>
<u>livymorph\.irrmagnus43</u><u>lexent\.n27649</u>maiorum<masc><gen><pl><comp><irregadj>
<u>livymorph\.irrmagnus44</u><u>lexent\.n27649</u>maioribus<masc><dat><pl><comp><irregadj>
<u>livymorph\.irrmagnus45</u><u>lexent\.n27649</u>maiores<masc><acc><pl><comp><irregadj>
<u>livymorph\.irrmagnus45b</u><u>lexent\.n27649</u>maioris<masc><acc><pl><comp><irregadj>
<u>livymorph\.irrmagnus46</u><u>lexent\.n27649</u>maioribus<masc><abl><pl><comp><irregadj>
<u>livymorph\.irrmagnus47</u><u>lexent\.n27649</u>maior<masc><voc><sg><comp><irregadj>
<u>livymorph\.irrmagnus48</u><u>lexent\.n27649</u>maiores<masc><voc><pl><comp><irregadj>
<u>livymorph\.irrmagnus49</u><u>lexent\.n27649</u>maior<fem><nom><sg><comp><irregadj>
<u>livymorph\.irrmagnus50</u><u>lexent\.n27649</u>maioris<fem><gen><sg><comp><irregadj>
<u>livymorph\.irrmagnus51</u><u>lexent\.n27649</u>maiori<fem><dat><sg><comp><irregadj>
<u>livymorph\.irrmagnus52</u><u>lexent\.n27649</u>maiorem<fem><acc><sg><comp><irregadj>
<u>livymorph\.irrmagnus53</u><u>lexent\.n27649</u>maiore<fem><abl><sg><comp><irregadj>
<u>livymorph\.irrmagnus53b</u><u>lexent\.n27649</u>maiori<fem><abl><sg><comp><irregadj>
<u>livymorph\.irrmagnus54</u><u>lexent\.n27649</u>maiores<fem><nom><pl><comp><irregadj>
<u>livymorph\.irrmagnus55</u><u>lexent\.n27649</u>maiorum<fem><gen><pl><comp><irregadj>
<u>livymorph\.irrmagnus56</u><u>lexent\.n27649</u>maioribus<fem><dat><pl><comp><irregadj>
<u>livymorph\.irrmagnus57</u><u>lexent\.n27649</u>maiores<fem><acc><pl><comp><irregadj>
<u>livymorph\.irrmagnus57b</u><u>lexent\.n27649</u>maioris<fem><acc><pl><comp><irregadj>
<u>livymorph\.irrmagnus58</u><u>lexent\.n27649</u>maioribus<fem><abl><pl><comp><irregadj>
<u>livymorph\.irrmagnus59</u><u>lexent\.n27649</u>maior<fem><voc><sg><comp><irregadj>
<u>livymorph\.irrmagnus60</u><u>lexent\.n27649</u>maiores<fem><voc><pl><comp><irregadj>
<u>livymorph\.irrmagnus61</u><u>lexent\.n27649</u>maius<neut><nom><sg><comp><irregadj>
<u>livymorph\.irrmagnus62</u><u>lexent\.n27649</u>maioris<neut><gen><sg><comp><irregadj>
<u>livymorph\.irrmagnus63</u><u>lexent\.n27649</u>maiori<neut><dat><sg><comp><irregadj>
<u>livymorph\.irrmagnus64</u><u>lexent\.n27649</u>maius<neut><acc><sg><comp><irregadj>
<u>livymorph\.irrmagnus65</u><u>lexent\.n27649</u>maiore<neut><abl><sg><comp><irregadj>
<u>livymorph\.irrmagnus65b</u><u>lexent\.n27649</u>maiori<neut><abl><sg><comp><irregadj>
<u>livymorph\.irrmagnus66</u><u>lexent\.n27649</u>maiora<neut><nom><pl><comp><irregadj>
<u>livymorph\.irrmagnus67</u><u>lexent\.n27649</u>maiorum<neut><gen><pl><comp><irregadj>
<u>livymorph\.irrmagnus68</u><u>lexent\.n27649</u>maioribus<neut><dat><pl><comp><irregadj>
<u>livymorph\.irrmagnus69</u><u>lexent\.n27649</u>maiora<neut><acc><pl><comp><irregadj>
<u>livymorph\.irrmagnus70</u><u>lexent\.n27649</u>maioribus<neut><abl><pl><comp><irregadj>
<u>livymorph\.irrmagnus71</u><u>lexent\.n27649</u>maius<neut><voc><sg><comp><irregadj>
<u>livymorph\.irrmagnus72</u><u>lexent\.n27649</u>maiora<neut><voc><pl><comp><irregadj>
<u>livymorph\.irrmagnus73</u><u>lexent\.n27649</u>maximus<masc><nom><sg><superl><irregadj>
<u>livymorph\.irrmagnus74</u><u>lexent\.n27649</u>maximi<masc><gen><sg><superl><irregadj>
<u>livymorph\.irrmagnus75</u><u>lexent\.n27649</u>maximo<masc><dat><sg><superl><irregadj>
<u>livymorph\.irrmagnus76</u><u>lexent\.n27649</u>maximum<masc><acc><sg><superl><irregadj>
<u>livymorph\.irrmagnus77</u><u>lexent\.n27649</u>maximo<masc><abl><sg><superl><irregadj>
<u>livymorph\.irrmagnus78</u><u>lexent\.n27649</u>maximi<masc><nom><pl><superl><irregadj>
<u>livymorph\.irrmagnus79</u><u>lexent\.n27649</u>maximorum<masc><gen><pl><superl><irregadj>
<u>livymorph\.irrmagnus80</u><u>lexent\.n27649</u>maximis<masc><dat><pl><superl><irregadj>
<u>livymorph\.irrmagnus81</u><u>lexent\.n27649</u>maximos<masc><acc><pl><superl><irregadj>
<u>livymorph\.irrmagnus82</u><u>lexent\.n27649</u>maximis<masc><abl><pl><superl><irregadj>
<u>livymorph\.irrmagnus83</u><u>lexent\.n27649</u>maxime<masc><voc><sg><superl><irregadj>
<u>livymorph\.irrmagnus84</u><u>lexent\.n27649</u>maximi<masc><voc><pl><superl><irregadj>
<u>livymorph\.irrmagnus85</u><u>lexent\.n27649</u>maxima<fem><nom><sg><superl><irregadj>
<u>livymorph\.irrmagnus86</u><u>lexent\.n27649</u>maximae<fem><gen><sg><superl><irregadj>
<u>livymorph\.irrmagnus87</u><u>lexent\.n27649</u>maximae<fem><dat><sg><superl><irregadj>
<u>livymorph\.irrmagnus88</u><u>lexent\.n27649</u>maximam<fem><acc><sg><superl><irregadj>
<u>livymorph\.irrmagnus89</u><u>lexent\.n27649</u>maxima<fem><abl><sg><superl><irregadj>
<u>livymorph\.irrmagnus90</u><u>lexent\.n27649</u>maximae<fem><nom><pl><superl><irregadj>
<u>livymorph\.irrmagnus91</u><u>lexent\.n27649</u>maximarum<fem><gen><pl><superl><irregadj>
<u>livymorph\.irrmagnus92</u><u>lexent\.n27649</u>maximis<fem><dat><pl><superl><irregadj>
<u>livymorph\.irrmagnus93</u><u>lexent\.n27649</u>maximas<fem><acc><pl><superl><irregadj>
<u>livymorph\.irrmagnus94</u><u>lexent\.n27649</u>maximis<fem><abl><pl><superl><irregadj>
<u>livymorph\.irrmagnus95</u><u>lexent\.n27649</u>maxima<fem><voc><sg><superl><irregadj>
<u>livymorph\.irrmagnus96</u><u>lexent\.n27649</u>maximae<fem><voc><pl><superl><irregadj>
<u>livymorph\.irrmagnus97</u><u>lexent\.n27649</u>maximum<neut><nom><sg><superl><irregadj>
<u>livymorph\.irrmagnus98</u><u>lexent\.n27649</u>maximi<neut><gen><sg><superl><irregadj>
<u>livymorph\.irrmagnus99</u><u>lexent\.n27649</u>maximo<neut><dat><sg><superl><irregadj>
<u>livymorph\.irrmagnus100</u><u>lexent\.n27649</u>maximum<neut><acc><sg><superl><irregadj>
<u>livymorph\.irrmagnus101</u><u>lexent\.n27649</u>maximo<neut><abl><sg><superl><irregadj>
<u>livymorph\.irrmagnus102</u><u>lexent\.n27649</u>maxima<neut><nom><pl><superl><irregadj>
<u>livymorph\.irrmagnus103</u><u>lexent\.n27649</u>maximorum<neut><gen><pl><superl><irregadj>
<u>livymorph\.irrmagnus104</u><u>lexent\.n27649</u>maximis<neut><dat><pl><superl><irregadj>
<u>livymorph\.irrmagnus105</u><u>lexent\.n27649</u>maxima<neut><acc><pl><superl><irregadj>
<u>livymorph\.irrmagnus106</u><u>lexent\.n27649</u>maximis<neut><abl><pl><superl><irregadj>
<u>livymorph\.irrmagnus107</u><u>lexent\.n27649</u>maximum<neut><voc><sg><superl><irregadj>
<u>livymorph\.irrmagnus108</u><u>lexent\.n27649</u>maxima<neut><voc><pl><superl><irregadj>

<u>livymorph\.irrmultus1</u><u>lexent\.n29945</u>multus<masc><nom><sg><pos><irregadj>
<u>livymorph\.irrmultus2</u><u>lexent\.n29945</u>multi<masc><gen><sg><pos><irregadj>
<u>livymorph\.irrmultus3</u><u>lexent\.n29945</u>multo<masc><dat><sg><pos><irregadj>
<u>livymorph\.irrmultus4</u><u>lexent\.n29945</u>multum<masc><acc><sg><pos><irregadj>
<u>livymorph\.irrmultus5</u><u>lexent\.n29945</u>multo<masc><abl><sg><pos><irregadj>
<u>livymorph\.irrmultus6</u><u>lexent\.n29945</u>multi<masc><nom><pl><pos><irregadj>
<u>livymorph\.irrmultus7</u><u>lexent\.n29945</u>multorum<masc><gen><pl><pos><irregadj>
<u>livymorph\.irrmultus8</u><u>lexent\.n29945</u>multis<masc><dat><pl><pos><irregadj>
<u>livymorph\.irrmultus9</u><u>lexent\.n29945</u>multos<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrmultus10</u><u>lexent\.n29945</u>multis<masc><abl><pl><pos><irregadj>
<u>livymorph\.irrmultus11</u><u>lexent\.n29945</u>multe<masc><voc><sg><pos><irregadj>
<u>livymorph\.irrmultus12</u><u>lexent\.n29945</u>multi<masc><voc><pl><pos><irregadj>
<u>livymorph\.irrmultus13</u><u>lexent\.n29945</u>multa<fem><nom><sg><pos><irregadj>
<u>livymorph\.irrmultus14</u><u>lexent\.n29945</u>multae<fem><gen><sg><pos><irregadj>
<u>livymorph\.irrmultus15</u><u>lexent\.n29945</u>multae<fem><dat><sg><pos><irregadj>
<u>livymorph\.irrmultus16</u><u>lexent\.n29945</u>multam<fem><acc><sg><pos><irregadj>
<u>livymorph\.irrmultus17</u><u>lexent\.n29945</u>multa<fem><abl><sg><pos><irregadj>
<u>livymorph\.irrmultus18</u><u>lexent\.n29945</u>multae<fem><nom><pl><pos><irregadj>
<u>livymorph\.irrmultus19</u><u>lexent\.n29945</u>multarum<fem><gen><pl><pos><irregadj>
<u>livymorph\.irrmultus20</u><u>lexent\.n29945</u>multis<fem><dat><pl><pos><irregadj>
<u>livymorph\.irrmultus21</u><u>lexent\.n29945</u>multas<fem><acc><pl><pos><irregadj>
<u>livymorph\.irrmultus22</u><u>lexent\.n29945</u>multis<fem><abl><pl><pos><irregadj>
<u>livymorph\.irrmultus23</u><u>lexent\.n29945</u>multa<fem><voc><sg><pos><irregadj>
<u>livymorph\.irrmultus24</u><u>lexent\.n29945</u>multae<fem><voc><pl><pos><irregadj>
<u>livymorph\.irrmultus25</u><u>lexent\.n29945</u>multum<neut><nom><sg><pos><irregadj>
<u>livymorph\.irrmultus26</u><u>lexent\.n29945</u>multi<neut><gen><sg><pos><irregadj>
<u>livymorph\.irrmultus27</u><u>lexent\.n29945</u>multo<neut><dat><sg><pos><irregadj>
<u>livymorph\.irrmultus28</u><u>lexent\.n29945</u>multum<neut><acc><sg><pos><irregadj>
<u>livymorph\.irrmultus29</u><u>lexent\.n29945</u>multo<neut><abl><sg><pos><irregadj>
<u>livymorph\.irrmultus30</u><u>lexent\.n29945</u>multa<neut><nom><pl><pos><irregadj>
<u>livymorph\.irrmultus31</u><u>lexent\.n29945</u>multorum<neut><gen><pl><pos><irregadj>
<u>livymorph\.irrmultus32</u><u>lexent\.n29945</u>multis<neut><dat><pl><pos><irregadj>
<u>livymorph\.irrmultus33</u><u>lexent\.n29945</u>multa<neut><acc><pl><pos><irregadj>
<u>livymorph\.irrmultus34</u><u>lexent\.n29945</u>multis<neut><abl><pl><pos><irregadj>
<u>livymorph\.irrmultus35</u><u>lexent\.n29945</u>multum<neut><voc><sg><pos><irregadj>
<u>livymorph\.irrmultus36</u><u>lexent\.n29945</u>multa<neut><voc><pl><pos><irregadj>
<u>livymorph\.irrmultus37</u><u>lexent\.n29945</u>plus<neut><nom><sg><comp><irregadj>
<u>livymorph\.irrmultus38</u><u>lexent\.n29945</u>pluris<neut><gen><sg><comp><irregadj>
<u>livymorph\.irrmultus39</u><u>lexent\.n29945</u>plus<neut><acc><sg><comp><irregadj>
<u>livymorph\.irrmultus40</u><u>lexent\.n29945</u>plure<neut><abl><sg><comp><irregadj>
<u>livymorph\.irrmultus41</u><u>lexent\.n29945</u>plura<neut><nom><pl><comp><irregadj>
<u>livymorph\.irrmultus42</u><u>lexent\.n29945</u>plurium<neut><gen><pl><comp><irregadj>
<u>livymorph\.irrmultus43</u><u>lexent\.n29945</u>pluribus<neut><dat><pl><comp><irregadj>
<u>livymorph\.irrmultus44</u><u>lexent\.n29945</u>plura<neut><acc><pl><comp><irregadj>
<u>livymorph\.irrmultus45</u><u>lexent\.n29945</u>pluribus<masc><abl><pl><comp><irregadj>
<u>livymorph\.irrmultus46</u><u>lexent\.n29945</u>plus<neut><voc><sg><comp><irregadj>
<u>livymorph\.irrmultus47</u><u>lexent\.n29945</u>plura<neut><voc><pl><comp><irregadj>
<u>livymorph\.irrmultus48</u><u>lexent\.n29945</u>plures<masc><nom><pl><comp><irregadj>
<u>livymorph\.irrmultus49</u><u>lexent\.n29945</u>plurium<masc><gen><pl><comp><irregadj>
<u>livymorph\.irrmultus50</u><u>lexent\.n29945</u>pluribus<masc><dat><pl><comp><irregadj>
<u>livymorph\.irrmultus51</u><u>lexent\.n29945</u>plures<masc><acc><pl><comp><irregadj>
<u>livymorph\.irrmultus51b</u><u>lexent\.n29945</u>pluris<masc><acc><pl><comp><irregadj>
<u>livymorph\.irrmultus52</u><u>lexent\.n29945</u>pluribus<masc><abl><pl><comp><irregadj>
<u>livymorph\.irrmultus53</u><u>lexent\.n29945</u>plures<masc><voc><pl><comp><irregadj>
<u>livymorph\.irrmultus54</u><u>lexent\.n29945</u>plures<fem><nom><pl><comp><irregadj>
<u>livymorph\.irrmultus55</u><u>lexent\.n29945</u>plurium<fem><gen><pl><comp><irregadj>
<u>livymorph\.irrmultus56</u><u>lexent\.n29945</u>pluribus<fem><dat><pl><comp><irregadj>
<u>livymorph\.irrmultus57</u><u>lexent\.n29945</u>plures<fem><acc><pl><comp><irregadj>
<u>livymorph\.irrmultus57b</u><u>lexent\.n29945</u>pluris<fem><acc><pl><comp><irregadj>
<u>livymorph\.irrmultus58</u><u>lexent\.n29945</u>pluribus<fem><abl><pl><comp><irregadj>
<u>livymorph\.irrmultus59</u><u>lexent\.n29945</u>plures<fem><voc><pl><comp><irregadj>
<u>livymorph\.irrmultus60</u><u>lexent\.n29945</u>plurimus<masc><nom><sg><superl><irregadj>
<u>livymorph\.irrmultus61</u><u>lexent\.n29945</u>plurimi<masc><gen><sg><superl><irregadj>
<u>livymorph\.irrmultus62</u><u>lexent\.n29945</u>plurimo<masc><dat><sg><superl><irregadj>
<u>livymorph\.irrmultus63</u><u>lexent\.n29945</u>plurimum<masc><acc><sg><superl><irregadj>
<u>livymorph\.irrmultus64</u><u>lexent\.n29945</u>plurimo<masc><abl><sg><superl><irregadj>
<u>livymorph\.irrmultus65</u><u>lexent\.n29945</u>plurimi<masc><nom><pl><superl><irregadj>
<u>livymorph\.irrmultus66</u><u>lexent\.n29945</u>plurimorum<masc><gen><pl><superl><irregadj>
<u>livymorph\.irrmultus67</u><u>lexent\.n29945</u>plurimis<masc><dat><pl><superl><irregadj>
<u>livymorph\.irrmultus68</u><u>lexent\.n29945</u>plurimos<masc><acc><pl><superl><irregadj>
<u>livymorph\.irrmultus69</u><u>lexent\.n29945</u>plurimis<masc><abl><pl><superl><irregadj>
<u>livymorph\.irrmultus70</u><u>lexent\.n29945</u>plurime<masc><voc><sg><superl><irregadj>
<u>livymorph\.irrmultus71</u><u>lexent\.n29945</u>plurimi<masc><voc><pl><superl><irregadj>
<u>livymorph\.irrmultus72</u><u>lexent\.n29945</u>plurima<fem><nom><sg><superl><irregadj>
<u>livymorph\.irrmultus73</u><u>lexent\.n29945</u>plurimae<fem><gen><sg><superl><irregadj>
<u>livymorph\.irrmultus74</u><u>lexent\.n29945</u>plurimae<fem><dat><sg><superl><irregadj>
<u>livymorph\.irrmultus75</u><u>lexent\.n29945</u>plurimam<fem><acc><sg><superl><irregadj>
<u>livymorph\.irrmultus76</u><u>lexent\.n29945</u>plurima<fem><abl><sg><superl><irregadj>
<u>livymorph\.irrmultus77</u><u>lexent\.n29945</u>plurimae<fem><nom><pl><superl><irregadj>
<u>livymorph\.irrmultus78</u><u>lexent\.n29945</u>plurimarum<fem><gen><pl><superl><irregadj>
<u>livymorph\.irrmultus79</u><u>lexent\.n29945</u>plurimis<fem><dat><pl><superl><irregadj>
<u>livymorph\.irrmultus80</u><u>lexent\.n29945</u>plurimas<fem><acc><pl><superl><irregadj>
<u>livymorph\.irrmultus81</u><u>lexent\.n29945</u>plurimis<fem><abl><pl><superl><irregadj>
<u>livymorph\.irrmultus82</u><u>lexent\.n29945</u>plurima<fem><voc><sg><superl><irregadj>
<u>livymorph\.irrmultus83</u><u>lexent\.n29945</u>plurimae<fem><voc><pl><superl><irregadj>
<u>livymorph\.irrmultus84</u><u>lexent\.n29945</u>plurimum<neut><nom><sg><superl><irregadj>
<u>livymorph\.irrmultus85</u><u>lexent\.n29945</u>plurimi<neut><gen><sg><superl><irregadj>
<u>livymorph\.irrmultus86</u><u>lexent\.n29945</u>plurimo<neut><dat><sg><superl><irregadj>
<u>livymorph\.irrmultus87</u><u>lexent\.n29945</u>plurimum<neut><acc><sg><superl><irregadj>
<u>livymorph\.irrmultus88</u><u>lexent\.n29945</u>plurimo<neut><abl><sg><superl><irregadj>
<u>livymorph\.irrmultus89</u><u>lexent\.n29945</u>plurima<neut><nom><pl><superl><irregadj>
<u>livymorph\.irrmultus90</u><u>lexent\.n29945</u>plurimorum<neut><gen><pl><superl><irregadj>
<u>livymorph\.irrmultus91</u><u>lexent\.n29945</u>plurimis<neut><dat><pl><superl><irregadj>
<u>livymorph\.irrmultus92</u><u>lexent\.n29945</u>plurima<neut><acc><pl><superl><irregadj>
<u>livymorph\.irrmultus93</u><u>lexent\.n29945</u>plurimis<neut><abl><pl><superl><irregadj>
<u>livymorph\.irrmultus94</u><u>lexent\.n29945</u>plurimum<neut><voc><sg><superl><irregadj>
<u>livymorph\.irrmultus95</u><u>lexent\.n29945</u>plurima<neut><voc><pl><superl><irregadj>

<u>livymorph\.irrparvus1</u><u>lexent\.n34005</u>parvus<masc><nom><sg><pos><irregadj>
<u>livymorph\.irrparvus2</u><u>lexent\.n34005</u>parvi<masc><gen><sg><pos><irregadj>
<u>livymorph\.irrparvus3</u><u>lexent\.n34005</u>parvo<masc><dat><sg><pos><irregadj>
<u>livymorph\.irrparvus4</u><u>lexent\.n34005</u>parvum<masc><acc><sg><pos><irregadj>
<u>livymorph\.irrparvus5</u><u>lexent\.n34005</u>parvo<masc><abl><sg><pos><irregadj>
<u>livymorph\.irrparvus6</u><u>lexent\.n34005</u>parvi<masc><nom><pl><pos><irregadj>
<u>livymorph\.irrparvus7</u><u>lexent\.n34005</u>parvorum<masc><gen><pl><pos><irregadj>
<u>livymorph\.irrparvus8</u><u>lexent\.n34005</u>parvis<masc><dat><pl><pos><irregadj>
<u>livymorph\.irrparvus9</u><u>lexent\.n34005</u>parvos<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrparvus10</u><u>lexent\.n34005</u>parvis<masc><abl><pl><pos><irregadj>
<u>livymorph\.irrparvus11</u><u>lexent\.n34005</u>parve<masc><voc><sg><pos><irregadj>
<u>livymorph\.irrparvus12</u><u>lexent\.n34005</u>parvi<masc><voc><pl><pos><irregadj>
<u>livymorph\.irrparvus13</u><u>lexent\.n34005</u>parva<fem><nom><sg><pos><irregadj>
<u>livymorph\.irrparvus14</u><u>lexent\.n34005</u>parvae<fem><gen><sg><pos><irregadj>
<u>livymorph\.irrparvus15</u><u>lexent\.n34005</u>parvae<fem><dat><sg><pos><irregadj>
<u>livymorph\.irrparvus16</u><u>lexent\.n34005</u>parvam<fem><acc><sg><pos><irregadj>
<u>livymorph\.irrparvus17</u><u>lexent\.n34005</u>parva<fem><abl><sg><pos><irregadj>
<u>livymorph\.irrparvus18</u><u>lexent\.n34005</u>parvae<fem><nom><pl><pos><irregadj>
<u>livymorph\.irrparvus19</u><u>lexent\.n34005</u>parvarum<fem><gen><pl><pos><irregadj>
<u>livymorph\.irrparvus20</u><u>lexent\.n34005</u>parvis<fem><dat><pl><pos><irregadj>
<u>livymorph\.irrparvus21</u><u>lexent\.n34005</u>parvas<fem><acc><pl><pos><irregadj>
<u>livymorph\.irrparvus22</u><u>lexent\.n34005</u>parvis<fem><abl><pl><pos><irregadj>
<u>livymorph\.irrparvus23</u><u>lexent\.n34005</u>parva<fem><voc><sg><pos><irregadj>
<u>livymorph\.irrparvus24</u><u>lexent\.n34005</u>parvae<fem><voc><pl><pos><irregadj>
<u>livymorph\.irrparvus25</u><u>lexent\.n34005</u>parvum<neut><nom><sg><pos><irregadj>
<u>livymorph\.irrparvus26</u><u>lexent\.n34005</u>parvi<neut><gen><sg><pos><irregadj>
<u>livymorph\.irrparvus27</u><u>lexent\.n34005</u>parvo<neut><dat><sg><pos><irregadj>
<u>livymorph\.irrparvus28</u><u>lexent\.n34005</u>parvum<neut><acc><sg><pos><irregadj>
<u>livymorph\.irrparvus29</u><u>lexent\.n34005</u>parvo<neut><abl><sg><pos><irregadj>
<u>livymorph\.irrparvus30</u><u>lexent\.n34005</u>parva<neut><nom><pl><pos><irregadj>
<u>livymorph\.irrparvus31</u><u>lexent\.n34005</u>parvorum<neut><gen><pl><pos><irregadj>
<u>livymorph\.irrparvus32</u><u>lexent\.n34005</u>parvis<neut><dat><pl><pos><irregadj>
<u>livymorph\.irrparvus33</u><u>lexent\.n34005</u>parva<neut><acc><pl><pos><irregadj>
<u>livymorph\.irrparvus34</u><u>lexent\.n34005</u>parvis<neut><abl><pl><pos><irregadj>
<u>livymorph\.irrparvus35</u><u>lexent\.n34005</u>parvum<neut><voc><sg><pos><irregadj>
<u>livymorph\.irrparvus36</u><u>lexent\.n34005</u>parva<neut><voc><pl><pos><irregadj>
<u>livymorph\.irrparvus37</u><u>lexent\.n34005</u>minor<masc><nom><sg><comp><irregadj>
<u>livymorph\.irrparvus38</u><u>lexent\.n34005</u>minoris<masc><gen><sg><comp><irregadj>
<u>livymorph\.irrparvus39</u><u>lexent\.n34005</u>minori<masc><dat><sg><comp><irregadj>
<u>livymorph\.irrparvus40</u><u>lexent\.n34005</u>minorem<masc><acc><sg><comp><irregadj>
<u>livymorph\.irrparvus41</u><u>lexent\.n34005</u>minore<masc><abl><sg><comp><irregadj>
<u>livymorph\.irrparvus41b</u><u>lexent\.n34005</u>minori<masc><abl><sg><comp><irregadj>
<u>livymorph\.irrparvus42</u><u>lexent\.n34005</u>minores<masc><nom><pl><comp><irregadj>
<u>livymorph\.irrparvus43</u><u>lexent\.n34005</u>minorum<masc><gen><pl><comp><irregadj>
<u>livymorph\.irrparvus44</u><u>lexent\.n34005</u>minoribus<masc><dat><pl><comp><irregadj>
<u>livymorph\.irrparvus45</u><u>lexent\.n34005</u>minores<masc><acc><pl><comp><irregadj>
<u>livymorph\.irrparvus45b</u><u>lexent\.n34005</u>minoris<masc><acc><pl><comp><irregadj>
<u>livymorph\.irrparvus46</u><u>lexent\.n34005</u>minoribus<masc><abl><pl><comp><irregadj>
<u>livymorph\.irrparvus47</u><u>lexent\.n34005</u>minor<masc><voc><sg><comp><irregadj>
<u>livymorph\.irrparvus48</u><u>lexent\.n34005</u>minores<masc><voc><pl><comp><irregadj>
<u>livymorph\.irrparvus49</u><u>lexent\.n34005</u>minor<fem><nom><sg><comp><irregadj>
<u>livymorph\.irrparvus50</u><u>lexent\.n34005</u>minoris<fem><gen><sg><comp><irregadj>
<u>livymorph\.irrparvus51</u><u>lexent\.n34005</u>minori<fem><dat><sg><comp><irregadj>
<u>livymorph\.irrparvus52</u><u>lexent\.n34005</u>minorem<fem><acc><sg><comp><irregadj>
<u>livymorph\.irrparvus53</u><u>lexent\.n34005</u>minore<fem><abl><sg><comp><irregadj>
<u>livymorph\.irrparvus53b</u><u>lexent\.n34005</u>minori<fem><abl><sg><comp><irregadj>
<u>livymorph\.irrparvus54</u><u>lexent\.n34005</u>minores<fem><nom><pl><comp><irregadj>
<u>livymorph\.irrparvus55</u><u>lexent\.n34005</u>minorum<fem><gen><pl><comp><irregadj>
<u>livymorph\.irrparvus56</u><u>lexent\.n34005</u>minoribus<fem><dat><pl><comp><irregadj>
<u>livymorph\.irrparvus57</u><u>lexent\.n34005</u>minores<fem><acc><pl><comp><irregadj>
<u>livymorph\.irrparvus57b</u><u>lexent\.n34005</u>minoris<fem><acc><pl><comp><irregadj>
<u>livymorph\.irrparvus58</u><u>lexent\.n34005</u>minoribus<fem><abl><pl><comp><irregadj>
<u>livymorph\.irrparvus59</u><u>lexent\.n34005</u>minor<fem><voc><sg><comp><irregadj>
<u>livymorph\.irrparvus60</u><u>lexent\.n34005</u>minores<fem><voc><pl><comp><irregadj>
<u>livymorph\.irrparvus61</u><u>lexent\.n34005</u>minus<neut><nom><sg><comp><irregadj>
<u>livymorph\.irrparvus62</u><u>lexent\.n34005</u>minoris<neut><gen><sg><comp><irregadj>
<u>livymorph\.irrparvus63</u><u>lexent\.n34005</u>minori<neut><dat><sg><comp><irregadj>
<u>livymorph\.irrparvus64</u><u>lexent\.n34005</u>minus<neut><acc><sg><comp><irregadj>
<u>livymorph\.irrparvus65</u><u>lexent\.n34005</u>minore<neut><abl><sg><comp><irregadj>
<u>livymorph\.irrparvus65b</u><u>lexent\.n34005</u>minori<neut><abl><sg><comp><irregadj>
<u>livymorph\.irrparvus66</u><u>lexent\.n34005</u>minora<neut><nom><pl><comp><irregadj>
<u>livymorph\.irrparvus67</u><u>lexent\.n34005</u>minorum<neut><gen><pl><comp><irregadj>
<u>livymorph\.irrparvus68</u><u>lexent\.n34005</u>minoribus<neut><dat><pl><comp><irregadj>
<u>livymorph\.irrparvus69</u><u>lexent\.n34005</u>minora<neut><acc><pl><comp><irregadj>
<u>livymorph\.irrparvus70</u><u>lexent\.n34005</u>minoribus<neut><abl><pl><comp><irregadj>
<u>livymorph\.irrparvus71</u><u>lexent\.n34005</u>minus<neut><voc><sg><comp><irregadj>
<u>livymorph\.irrparvus72</u><u>lexent\.n34005</u>minora<neut><voc><pl><comp><irregadj>
<u>livymorph\.irrparvus73</u><u>lexent\.n34005</u>minimus<masc><nom><sg><superl><irregadj>
<u>livymorph\.irrparvus74</u><u>lexent\.n34005</u>minimi<masc><gen><sg><superl><irregadj>
<u>livymorph\.irrparvus75</u><u>lexent\.n34005</u>minimo<masc><dat><sg><superl><irregadj>
<u>livymorph\.irrparvus76</u><u>lexent\.n34005</u>minimum<masc><acc><sg><superl><irregadj>
<u>livymorph\.irrparvus77</u><u>lexent\.n34005</u>minimo<masc><abl><sg><superl><irregadj>
<u>livymorph\.irrparvus78</u><u>lexent\.n34005</u>minimi<masc><nom><pl><superl><irregadj>
<u>livymorph\.irrparvus79</u><u>lexent\.n34005</u>minimorum<masc><gen><pl><superl><irregadj>
<u>livymorph\.irrparvus80</u><u>lexent\.n34005</u>minimis<masc><dat><pl><superl><irregadj>
<u>livymorph\.irrparvus81</u><u>lexent\.n34005</u>minimos<masc><acc><pl><superl><irregadj>
<u>livymorph\.irrparvus82</u><u>lexent\.n34005</u>minimis<masc><abl><pl><superl><irregadj>
<u>livymorph\.irrparvus83</u><u>lexent\.n34005</u>minime<masc><voc><sg><superl><irregadj>
<u>livymorph\.irrparvus84</u><u>lexent\.n34005</u>minimi<masc><voc><pl><superl><irregadj>
<u>livymorph\.irrparvus85</u><u>lexent\.n34005</u>minima<fem><nom><sg><superl><irregadj>
<u>livymorph\.irrparvus86</u><u>lexent\.n34005</u>minimae<fem><gen><sg><superl><irregadj>
<u>livymorph\.irrparvus87</u><u>lexent\.n34005</u>minimae<fem><dat><sg><superl><irregadj>
<u>livymorph\.irrparvus88</u><u>lexent\.n34005</u>minimam<fem><acc><sg><superl><irregadj>
<u>livymorph\.irrparvus89</u><u>lexent\.n34005</u>minima<fem><abl><sg><superl><irregadj>
<u>livymorph\.irrparvus90</u><u>lexent\.n34005</u>minimae<fem><nom><pl><superl><irregadj>
<u>livymorph\.irrparvus91</u><u>lexent\.n34005</u>minimarum<fem><gen><pl><superl><irregadj>
<u>livymorph\.irrparvus92</u><u>lexent\.n34005</u>minimis<fem><dat><pl><superl><irregadj>
<u>livymorph\.irrparvus93</u><u>lexent\.n34005</u>minimas<fem><acc><pl><superl><irregadj>
<u>livymorph\.irrparvus94</u><u>lexent\.n34005</u>minimis<fem><abl><pl><superl><irregadj>
<u>livymorph\.irrparvus95</u><u>lexent\.n34005</u>minima<fem><voc><sg><superl><irregadj>
<u>livymorph\.irrparvus96</u><u>lexent\.n34005</u>minimae<fem><voc><pl><superl><irregadj>
<u>livymorph\.irrparvus97</u><u>lexent\.n34005</u>minimum<neut><nom><sg><superl><irregadj>
<u>livymorph\.irrparvus98</u><u>lexent\.n34005</u>minimi<neut><gen><sg><superl><irregadj>
<u>livymorph\.irrparvus99</u><u>lexent\.n34005</u>minimo<neut><dat><sg><superl><irregadj>
<u>livymorph\.irrparvus100</u><u>lexent\.n34005</u>minimum<neut><acc><sg><superl><irregadj>
<u>livymorph\.irrparvus101</u><u>lexent\.n34005</u>minimo<neut><abl><sg><superl><irregadj>
<u>livymorph\.irrparvus102</u><u>lexent\.n34005</u>minima<neut><nom><pl><superl><irregadj>
<u>livymorph\.irrparvus103</u><u>lexent\.n34005</u>minimorum<neut><gen><pl><superl><irregadj>
<u>livymorph\.irrparvus104</u><u>lexent\.n34005</u>minimis<neut><dat><pl><superl><irregadj>
<u>livymorph\.irrparvus105</u><u>lexent\.n34005</u>minima<neut><acc><pl><superl><irregadj>
<u>livymorph\.irrparvus106</u><u>lexent\.n34005</u>minimis<neut><abl><pl><superl><irregadj>
<u>livymorph\.irrparvus107</u><u>lexent\.n34005</u>minimum<neut><voc><sg><superl><irregadj>
<u>livymorph\.irrparvus108</u><u>lexent\.n34005</u>minima<neut><voc><pl><superl><irregadj>

<u>livymorph\.irrtot1</u><u>lexent\.n48622</u>tot<masc><nom><pl><pos><irregadj>
<u>livymorph\.irrtot2</u><u>lexent\.n48622</u>tot<masc><gen><pl><pos><irregadj>
<u>livymorph\.irrtot3</u><u>lexent\.n48622</u>tot<masc><dat><pl><pos><irregadj>
<u>livymorph\.irrtot4</u><u>lexent\.n48622</u>tot<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrtot5</u><u>lexent\.n48622</u>tot<masc><abl><pl><pos><irregadj>
<u>livymorph\.irrtot6</u><u>lexent\.n48622</u>tot<fem><nom><pl><pos><irregadj>
<u>livymorph\.irrtot7</u><u>lexent\.n48622</u>tot<fem><gen><pl><pos><irregadj>
<u>livymorph\.irrtot8</u><u>lexent\.n48622</u>tot<fem><dat><pl><pos><irregadj>
<u>livymorph\.irrtot9</u><u>lexent\.n48622</u>tot<fem><acc><pl><pos><irregadj>
<u>livymorph\.irrtot10</u><u>lexent\.n48622</u>tot<fem><abl><pl><pos><irregadj>
<u>livymorph\.irrtot11</u><u>lexent\.n48622</u>tot<neut><nom><pl><pos><irregadj>
<u>livymorph\.irrtot12</u><u>lexent\.n48622</u>tot<neut><gen><pl><pos><irregadj>
<u>livymorph\.irrtot13</u><u>lexent\.n48622</u>tot<neut><dat><pl><pos><irregadj>
<u>livymorph\.irrtot14</u><u>lexent\.n48622</u>tot<neut><acc><pl><pos><irregadj>
<u>livymorph\.irrtot15</u><u>lexent\.n48622</u>tot<neut><abl><pl><pos><irregadj>

<u>livymorph\.irrtotus1</u><u>lexent\.n48627</u>totus<masc><nom><sg><pos><irregadj>
<u>livymorph\.irrtotus2</u><u>lexent\.n48627</u>totius<masc><gen><sg><pos><irregadj>
<u>livymorph\.irrtotus3</u><u>lexent\.n48627</u>toti<masc><dat><sg><pos><irregadj>
<u>livymorph\.irrtotus4</u><u>lexent\.n48627</u>totum<masc><acc><sg><pos><irregadj>
<u>livymorph\.irrtotus5</u><u>lexent\.n48627</u>toto<masc><abl><sg><pos><irregadj>
<u>livymorph\.irrtotus6</u><u>lexent\.n48627</u>toti<masc><nom><pl><pos><irregadj>
<u>livymorph\.irrtotus7</u><u>lexent\.n48627</u>totorum<masc><gen><pl><pos><irregadj>
<u>livymorph\.irrtotus8</u><u>lexent\.n48627</u>totis<masc><dat><pl><pos><irregadj>
<u>livymorph\.irrtotus9</u><u>lexent\.n48627</u>totos<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrtotus10</u><u>lexent\.n48627</u>totis<masc><abl><pl><pos><irregadj>
<u>livymorph\.irrtotus11</u><u>lexent\.n48627</u>tote<masc><voc><sg><pos><irregadj>
<u>livymorph\.irrtotus12</u><u>lexent\.n48627</u>toti<masc><voc><pl><pos><irregadj>
<u>livymorph\.irrtotus13</u><u>lexent\.n48627</u>tota<fem><nom><sg><pos><irregadj>
<u>livymorph\.irrtotus14</u><u>lexent\.n48627</u>totius<fem><gen><sg><pos><irregadj>
<u>livymorph\.irrtotus15</u><u>lexent\.n48627</u>toti<fem><dat><sg><pos><irregadj>
<u>livymorph\.irrtotus16</u><u>lexent\.n48627</u>totam<fem><acc><sg><pos><irregadj>
<u>livymorph\.irrtotus17</u><u>lexent\.n48627</u>tota<fem><abl><sg><pos><irregadj>
<u>livymorph\.irrtotus18</u><u>lexent\.n48627</u>totae<fem><nom><pl><pos><irregadj>
<u>livymorph\.irrtotus19</u><u>lexent\.n48627</u>totarum<fem><gen><pl><pos><irregadj>
<u>livymorph\.irrtotus20</u><u>lexent\.n48627</u>totis<fem><dat><pl><pos><irregadj>
<u>livymorph\.irrtotus21</u><u>lexent\.n48627</u>totas<fem><acc><pl><pos><irregadj>
<u>livymorph\.irrtotus22</u><u>lexent\.n48627</u>totis<fem><abl><pl><pos><irregadj>
<u>livymorph\.irrtotus23</u><u>lexent\.n48627</u>tota<fem><voc><sg><pos><irregadj>
<u>livymorph\.irrtotus24</u><u>lexent\.n48627</u>totae<fem><voc><pl><pos><irregadj>
<u>livymorph\.irrtotus25</u><u>lexent\.n48627</u>totum<neut><nom><sg><pos><irregadj>
<u>livymorph\.irrtotus26</u><u>lexent\.n48627</u>totius<neut><gen><sg><pos><irregadj>
<u>livymorph\.irrtotus27</u><u>lexent\.n48627</u>toti<neut><dat><sg><pos><irregadj>
<u>livymorph\.irrtotus28</u><u>lexent\.n48627</u>totum<neut><acc><sg><pos><irregadj>
<u>livymorph\.irrtotus29</u><u>lexent\.n48627</u>toto<neut><abl><sg><pos><irregadj>
<u>livymorph\.irrtotus30</u><u>lexent\.n48627</u>tota<neut><nom><pl><pos><irregadj>
<u>livymorph\.irrtotus31</u><u>lexent\.n48627</u>totorum<neut><gen><pl><pos><irregadj>
<u>livymorph\.irrtotus32</u><u>lexent\.n48627</u>totis<neut><dat><pl><pos><irregadj>
<u>livymorph\.irrtotus33</u><u>lexent\.n48627</u>tota<neut><acc><pl><pos><irregadj>
<u>livymorph\.irrtotus34</u><u>lexent\.n48627</u>totis<neut><abl><pl><pos><irregadj>
<u>livymorph\.irrtotus35</u><u>lexent\.n48627</u>totum<neut><voc><sg><pos><irregadj>
<u>livymorph\.irrtotus36</u><u>lexent\.n48627</u>tota<neut><voc><pl><pos><irregadj>

<u>livymorph\.irrtres1</u><u>lexent\.n48969</u>tres<masc><nom><pl><pos><irregadj>
<u>livymorph\.irrtres2</u><u>lexent\.n48969</u>trium<masc><gen><pl><pos><irregadj>
<u>livymorph\.irrtres3</u><u>lexent\.n48969</u>tribus<masc><dat><pl><pos><irregadj>
<u>livymorph\.irrtres4</u><u>lexent\.n48969</u>tres<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrtres4b</u><u>lexent\.n48969</u>tris<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrtres5</u><u>lexent\.n48969</u>tribus<masc><abl><pl><pos><irregadj>
<u>livymorph\.irrtres6</u><u>lexent\.n48969</u>tres<masc><voc><pl><pos><irregadj>
<u>livymorph\.irrtres7</u><u>lexent\.n48969</u>tres<fem><nom><pl><pos><irregadj>
<u>livymorph\.irrtres8</u><u>lexent\.n48969</u>trium<fem><gen><pl><pos><irregadj>
<u>livymorph\.irrtres9</u><u>lexent\.n48969</u>tribus<fem><dat><pl><pos><irregadj>
<u>livymorph\.irrtres10</u><u>lexent\.n48969</u>tres<fem><acc><pl><pos><irregadj>
<u>livymorph\.irrtres10b</u><u>lexent\.n48969</u>tris<fem><acc><pl><pos><irregadj>
<u>livymorph\.irrtres11</u><u>lexent\.n48969</u>tribus<fem><abl><pl><pos><irregadj>
<u>livymorph\.irrtres12</u><u>lexent\.n48969</u>tres<fem><voc><pl><pos><irregadj>
<u>livymorph\.irrtres13</u><u>lexent\.n48969</u>tria<neut><nom><pl><pos><irregadj>
<u>livymorph\.irrtres14</u><u>lexent\.n48969</u>trium<neut><gen><pl><pos><irregadj>
<u>livymorph\.irrtres15</u><u>lexent\.n48969</u>tribus<neut><dat><pl><pos><irregadj>
<u>livymorph\.irrtres16</u><u>lexent\.n48969</u>tria<neut><acc><pl><pos><irregadj>
<u>livymorph\.irrtres17</u><u>lexent\.n48969</u>tribus<neut><abl><pl><pos><irregadj>
<u>livymorph\.irrtres18</u><u>lexent\.n48969</u>tria<neut><voc><pl><pos><irregadj>

<u>livymorph\.irrullus1</u><u>lexent\.n49645</u>ullus<masc><nom><sg><pos><irregadj>
<u>livymorph\.irrullus2</u><u>lexent\.n49645</u>ullius<masc><gen><sg><pos><irregadj>
<u>livymorph\.irrullus3</u><u>lexent\.n49645</u>ulli<masc><dat><sg><pos><irregadj>
<u>livymorph\.irrullus4</u><u>lexent\.n49645</u>ullum<masc><acc><sg><pos><irregadj>
<u>livymorph\.irrullus5</u><u>lexent\.n49645</u>ullo<masc><abl><sg><pos><irregadj>
<u>livymorph\.irrullus6</u><u>lexent\.n49645</u>ulli<masc><nom><pl><pos><irregadj>
<u>livymorph\.irrullus7</u><u>lexent\.n49645</u>ullorum<masc><gen><pl><pos><irregadj>
<u>livymorph\.irrullus8</u><u>lexent\.n49645</u>ullis<masc><dat><pl><pos><irregadj>
<u>livymorph\.irrullus9</u><u>lexent\.n49645</u>ullos<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrullus10</u><u>lexent\.n49645</u>ullis<masc><abl><pl><pos><irregadj>
<u>livymorph\.irrullus11</u><u>lexent\.n49645</u>ulle<masc><voc><sg><pos><irregadj>
<u>livymorph\.irrullus12</u><u>lexent\.n49645</u>ulli<masc><voc><pl><pos><irregadj>
<u>livymorph\.irrullus13</u><u>lexent\.n49645</u>ulla<fem><nom><sg><pos><irregadj>
<u>livymorph\.irrullus14</u><u>lexent\.n49645</u>ullius<fem><gen><sg><pos><irregadj>
<u>livymorph\.irrullus15</u><u>lexent\.n49645</u>ulli<fem><dat><sg><pos><irregadj>
<u>livymorph\.irrullus16</u><u>lexent\.n49645</u>ullam<fem><acc><sg><pos><irregadj>
<u>livymorph\.irrullus17</u><u>lexent\.n49645</u>ulla<fem><abl><sg><pos><irregadj>
<u>livymorph\.irrullus18</u><u>lexent\.n49645</u>ullae<fem><nom><pl><pos><irregadj>
<u>livymorph\.irrullus19</u><u>lexent\.n49645</u>ullarum<fem><gen><pl><pos><irregadj>
<u>livymorph\.irrullus20</u><u>lexent\.n49645</u>ullis<fem><dat><pl><pos><irregadj>
<u>livymorph\.irrullus21</u><u>lexent\.n49645</u>ullas<fem><acc><pl><pos><irregadj>
<u>livymorph\.irrullus22</u><u>lexent\.n49645</u>ullis<fem><abl><pl><pos><irregadj>
<u>livymorph\.irrullus23</u><u>lexent\.n49645</u>ulla<fem><voc><sg><pos><irregadj>
<u>livymorph\.irrullus24</u><u>lexent\.n49645</u>ullae<fem><voc><pl><pos><irregadj>
<u>livymorph\.irrullus25</u><u>lexent\.n49645</u>ullum<neut><nom><sg><pos><irregadj>
<u>livymorph\.irrullus26</u><u>lexent\.n49645</u>ullius<neut><gen><sg><pos><irregadj>
<u>livymorph\.irrullus27</u><u>lexent\.n49645</u>ulli<neut><dat><sg><pos><irregadj>
<u>livymorph\.irrullus28</u><u>lexent\.n49645</u>ullum<neut><acc><sg><pos><irregadj>
<u>livymorph\.irrullus29</u><u>lexent\.n49645</u>ullo<neut><abl><sg><pos><irregadj>
<u>livymorph\.irrullus30</u><u>lexent\.n49645</u>ulla<neut><nom><pl><pos><irregadj>
<u>livymorph\.irrullus31</u><u>lexent\.n49645</u>ullorum<neut><gen><pl><pos><irregadj>
<u>livymorph\.irrullus32</u><u>lexent\.n49645</u>ullis<neut><dat><pl><pos><irregadj>
<u>livymorph\.irrullus33</u><u>lexent\.n49645</u>ulla<neut><acc><pl><pos><irregadj>
<u>livymorph\.irrullus34</u><u>lexent\.n49645</u>ullis<neut><abl><pl><pos><irregadj>
<u>livymorph\.irrullus35</u><u>lexent\.n49645</u>ullum<neut><voc><sg><pos><irregadj>
<u>livymorph\.irrullus36</u><u>lexent\.n49645</u>ulla<neut><voc><pl><pos><irregadj>

<u>livymorph\.irrunus1</u><u>lexent\.n49871</u>unus<masc><nom><sg><pos><irregadj>
<u>livymorph\.irrunus2</u><u>lexent\.n49871</u>unius<masc><gen><sg><pos><irregadj>
<u>livymorph\.irrunus3</u><u>lexent\.n49871</u>uni<masc><dat><sg><pos><irregadj>
<u>livymorph\.irrunus4</u><u>lexent\.n49871</u>unum<masc><acc><sg><pos><irregadj>
<u>livymorph\.irrunus5</u><u>lexent\.n49871</u>uno<masc><abl><sg><pos><irregadj>
<u>livymorph\.irrunus6</u><u>lexent\.n49871</u>uni<masc><nom><pl><pos><irregadj>
<u>livymorph\.irrunus7</u><u>lexent\.n49871</u>unorum<masc><gen><pl><pos><irregadj>
<u>livymorph\.irrunus8</u><u>lexent\.n49871</u>unis<masc><dat><pl><pos><irregadj>
<u>livymorph\.irrunus9</u><u>lexent\.n49871</u>unos<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrunus10</u><u>lexent\.n49871</u>unis<masc><abl><pl><pos><irregadj>
<u>livymorph\.irrunus11</u><u>lexent\.n49871</u>une<masc><voc><sg><pos><irregadj>
<u>livymorph\.irrunus12</u><u>lexent\.n49871</u>uni<masc><voc><pl><pos><irregadj>
<u>livymorph\.irrunus13</u><u>lexent\.n49871</u>una<fem><nom><sg><pos><irregadj>
<u>livymorph\.irrunus14</u><u>lexent\.n49871</u>unius<fem><gen><sg><pos><irregadj>
<u>livymorph\.irrunus15</u><u>lexent\.n49871</u>uni<fem><dat><sg><pos><irregadj>
<u>livymorph\.irrunus16</u><u>lexent\.n49871</u>unam<fem><acc><sg><pos><irregadj>
<u>livymorph\.irrunus17</u><u>lexent\.n49871</u>una<fem><abl><sg><pos><irregadj>
<u>livymorph\.irrunus18</u><u>lexent\.n49871</u>unae<fem><nom><pl><pos><irregadj>
<u>livymorph\.irrunus19</u><u>lexent\.n49871</u>unarum<fem><gen><pl><pos><irregadj>
<u>livymorph\.irrunus20</u><u>lexent\.n49871</u>unis<fem><dat><pl><pos><irregadj>
<u>livymorph\.irrunus21</u><u>lexent\.n49871</u>unas<fem><acc><pl><pos><irregadj>
<u>livymorph\.irrunus22</u><u>lexent\.n49871</u>unis<fem><abl><pl><pos><irregadj>
<u>livymorph\.irrunus23</u><u>lexent\.n49871</u>una<fem><voc><sg><pos><irregadj>
<u>livymorph\.irrunus24</u><u>lexent\.n49871</u>unae<fem><voc><pl><pos><irregadj>
<u>livymorph\.irrunus25</u><u>lexent\.n49871</u>unum<neut><nom><sg><pos><irregadj>
<u>livymorph\.irrunus26</u><u>lexent\.n49871</u>unius<neut><gen><sg><pos><irregadj>
<u>livymorph\.irrunus27</u><u>lexent\.n49871</u>uni<neut><dat><sg><pos><irregadj>
<u>livymorph\.irrunus28</u><u>lexent\.n49871</u>unum<neut><acc><sg><pos><irregadj>
<u>livymorph\.irrunus29</u><u>lexent\.n49871</u>uno<neut><abl><sg><pos><irregadj>
<u>livymorph\.irrunus30</u><u>lexent\.n49871</u>una<neut><nom><pl><pos><irregadj>
<u>livymorph\.irrunus31</u><u>lexent\.n49871</u>unorum<neut><gen><pl><pos><irregadj>
<u>livymorph\.irrunus32</u><u>lexent\.n49871</u>unis<neut><dat><pl><pos><irregadj>
<u>livymorph\.irrunus33</u><u>lexent\.n49871</u>una<neut><acc><pl><pos><irregadj>
<u>livymorph\.irrunus34</u><u>lexent\.n49871</u>unis<neut><abl><pl><pos><irregadj>
<u>livymorph\.irrunus35</u><u>lexent\.n49871</u>unum<neut><voc><sg><pos><irregadj>
<u>livymorph\.irrunus36</u><u>lexent\.n49871</u>una<neut><voc><pl><pos><irregadj>

<u>livymorph\.irrvetus1</u><u>lexent\.n2015</u>vetus<masc><nom><sg><pos><irregadj>
<u>livymorph\.irrvetus2</u><u>lexent\.n2015</u>veteris<masc><gen><sg><pos><irregadj>
<u>livymorph\.irrvetus3</u><u>lexent\.n2015</u>veteri<masc><dat><sg><pos><irregadj>
<u>livymorph\.irrvetus4</u><u>lexent\.n2015</u>veterem<masc><acc><sg><pos><irregadj>
<u>livymorph\.irrvetus5</u><u>lexent\.n2015</u>vetere<masc><abl><sg><pos><irregadj>
<u>livymorph\.irrvetus5b</u><u>lexent\.n2015</u>veteri<masc><abl><sg><pos><irregadj>
<u>livymorph\.irrvetus6</u><u>lexent\.n2015</u>veteres<masc><nom><pl><pos><irregadj>
<u>livymorph\.irrvetus7</u><u>lexent\.n2015</u>veterum<masc><gen><pl><pos><irregadj>
<u>livymorph\.irrvetus8</u><u>lexent\.n2015</u>veteribus<masc><dat><pl><pos><irregadj>
<u>livymorph\.irrvetus9</u><u>lexent\.n2015</u>veteres<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrvetus9b</u><u>lexent\.n2015</u>veteris<masc><acc><pl><pos><irregadj>
<u>livymorph\.irrvetus10</u><u>lexent\.n2015</u>veteribus<masc><abl><pl><pos><irregadj>
<u>livymorph\.irrvetus11</u><u>lexent\.n2015</u>vetus<masc><voc><sg><pos><irregadj>
<u>livymorph\.irrvetus12</u><u>lexent\.n2015</u>veteres<masc><voc><pl><pos><irregadj>
<u>livymorph\.irrvetus13</u><u>lexent\.n2015</u>vetus<fem><nom><sg><pos><irregadj>
<u>livymorph\.irrvetus14</u><u>lexent\.n2015</u>veteris<fem><gen><sg><pos><irregadj>
<u>livymorph\.irrvetus15</u><u>lexent\.n2015</u>veteri<fem><dat><sg><pos><irregadj>
<u>livymorph\.irrvetus16</u><u>lexent\.n2015</u>veterem<fem><acc><sg><pos><irregadj>
<u>livymorph\.irrvetus17</u><u>lexent\.n2015</u>vetere<fem><abl><sg><pos><irregadj>
<u>livymorph\.irrvetus17b</u><u>lexent\.n2015</u>veteri<fem><abl><sg><pos><irregadj>
<u>livymorph\.irrvetus18</u><u>lexent\.n2015</u>veteres<fem><nom><pl><pos><irregadj>
<u>livymorph\.irrvetus19</u><u>lexent\.n2015</u>veterum<fem><gen><pl><pos><irregadj>
<u>livymorph\.irrvetus20</u><u>lexent\.n2015</u>veteribus<fem><dat><pl><pos><irregadj>
<u>livymorph\.irrvetus21</u><u>lexent\.n2015</u>veteres<fem><acc><pl><pos><irregadj>
<u>livymorph\.irrvetus21b</u><u>lexent\.n2015</u>veteris<fem><acc><pl><pos><irregadj>
<u>livymorph\.irrvetus22</u><u>lexent\.n2015</u>veteribus<fem><abl><pl><pos><irregadj>
<u>livymorph\.irrvetus23</u><u>lexent\.n2015</u>vetus<fem><voc><sg><pos><irregadj>
<u>livymorph\.irrvetus24</u><u>lexent\.n2015</u>veteres<fem><voc><pl><pos><irregadj>
<u>livymorph\.irrvetus25</u><u>lexent\.n2015</u>vetus<neut><nom><sg><pos><irregadj>
<u>livymorph\.irrvetus26</u><u>lexent\.n2015</u>veteris<neut><gen><sg><pos><irregadj>
<u>livymorph\.irrvetus27</u><u>lexent\.n2015</u>veteri<neut><dat><sg><pos><irregadj>
<u>livymorph\.irrvetus28</u><u>lexent\.n2015</u>vetus<neut><acc><sg><pos><irregadj>
<u>livymorph\.irrvetus29</u><u>lexent\.n2015</u>vetere<neut><abl><sg><pos><irregadj>
<u>livymorph\.irrvetus29b</u><u>lexent\.n2015</u>veteri<neut><abl><sg><pos><irregadj>
<u>livymorph\.irrvetus30</u><u>lexent\.n2015</u>vetera<neut><nom><pl><pos><irregadj>
<u>livymorph\.irrvetus31</u><u>lexent\.n2015</u>veterum<neut><gen><pl><pos><irregadj>
<u>livymorph\.irrvetus32</u><u>lexent\.n2015</u>veteribus<neut><dat><pl><pos><irregadj>
<u>livymorph\.irrvetus33</u><u>lexent\.n2015</u>vetera<neut><acc><pl><pos><irregadj>
<u>livymorph\.irrvetus34</u><u>lexent\.n2015</u>veteribus<neut><abl><pl><pos><irregadj>
<u>livymorph\.irrvetus35</u><u>lexent\.n2015</u>vetus<neut><voc><sg><pos><irregadj>
<u>livymorph\.irrvetus36</u><u>lexent\.n2015</u>vetera<neut><voc><pl><pos><irregadj>
<u>livymorph\.irrvetus37</u><u>lexent\.n2015</u>vetustior<masc><nom><sg><comp><irregadj>
<u>livymorph\.irrvetus38</u><u>lexent\.n2015</u>vetustioris<masc><gen><sg><comp><irregadj>
<u>livymorph\.irrvetus39</u><u>lexent\.n2015</u>vetustiori<masc><dat><sg><comp><irregadj>
<u>livymorph\.irrvetus40</u><u>lexent\.n2015</u>vetustiorem<masc><acc><sg><comp><irregadj>
<u>livymorph\.irrvetus41</u><u>lexent\.n2015</u>vetustiore<masc><abl><sg><comp><irregadj>
<u>livymorph\.irrvetus41b</u><u>lexent\.n2015</u>vetustiori<masc><abl><sg><comp><irregadj>
<u>livymorph\.irrvetus42</u><u>lexent\.n2015</u>vetustiores<masc><nom><pl><comp><irregadj>
<u>livymorph\.irrvetus43</u><u>lexent\.n2015</u>vetustiorum<masc><gen><pl><comp><irregadj>
<u>livymorph\.irrvetus44</u><u>lexent\.n2015</u>vetustioribus<masc><dat><pl><comp><irregadj>
<u>livymorph\.irrvetus45</u><u>lexent\.n2015</u>vetustiores<masc><acc><pl><comp><irregadj>
<u>livymorph\.irrvetus45b</u><u>lexent\.n2015</u>vetustioris<masc><acc><pl><comp><irregadj>
<u>livymorph\.irrvetus46</u><u>lexent\.n2015</u>vetustioribus<masc><abl><pl><comp><irregadj>
<u>livymorph\.irrvetus47</u><u>lexent\.n2015</u>vetustior<masc><voc><sg><comp><irregadj>
<u>livymorph\.irrvetus48</u><u>lexent\.n2015</u>vetustiores<masc><voc><pl><comp><irregadj>
<u>livymorph\.irrvetus49</u><u>lexent\.n2015</u>vetustior<fem><nom><sg><comp><irregadj>
<u>livymorph\.irrvetus50</u><u>lexent\.n2015</u>vetustioris<fem><gen><sg><comp><irregadj>
<u>livymorph\.irrvetus51</u><u>lexent\.n2015</u>vetustiori<fem><dat><sg><comp><irregadj>
<u>livymorph\.irrvetus52</u><u>lexent\.n2015</u>vetustiorem<fem><acc><sg><comp><irregadj>
<u>livymorph\.irrvetus53</u><u>lexent\.n2015</u>vetustiore<fem><abl><sg><comp><irregadj>
<u>livymorph\.irrvetus53b</u><u>lexent\.n2015</u>vetustiori<fem><abl><sg><comp><irregadj>
<u>livymorph\.irrvetus54</u><u>lexent\.n2015</u>vetustiores<fem><nom><pl><comp><irregadj>
<u>livymorph\.irrvetus55</u><u>lexent\.n2015</u>vetustiorum<fem><gen><pl><comp><irregadj>
<u>livymorph\.irrvetus56</u><u>lexent\.n2015</u>vetustioribus<fem><dat><pl><comp><irregadj>
<u>livymorph\.irrvetus57</u><u>lexent\.n2015</u>vetustiores<fem><acc><pl><comp><irregadj>
<u>livymorph\.irrvetus57b</u><u>lexent\.n2015</u>vetustioris<fem><acc><pl><comp><irregadj>
<u>livymorph\.irrvetus58</u><u>lexent\.n2015</u>vetustioribus<fem><abl><pl><comp><irregadj>
<u>livymorph\.irrvetus59</u><u>lexent\.n2015</u>vetustior<fem><voc><sg><comp><irregadj>
<u>livymorph\.irrvetus60</u><u>lexent\.n2015</u>vetustiores<fem><voc><pl><comp><irregadj>
<u>livymorph\.irrvetus61</u><u>lexent\.n2015</u>vetustius<neut><nom><sg><comp><irregadj>
<u>livymorph\.irrvetus62</u><u>lexent\.n2015</u>vetustioris<neut><gen><sg><comp><irregadj>
<u>livymorph\.irrvetus63</u><u>lexent\.n2015</u>vetustiori<neut><dat><sg><comp><irregadj>
<u>livymorph\.irrvetus64</u><u>lexent\.n2015</u>vetustius<neut><acc><sg><comp><irregadj>
<u>livymorph\.irrvetus65</u><u>lexent\.n2015</u>vetustiore<neut><abl><sg><comp><irregadj>
<u>livymorph\.irrvetus65b</u><u>lexent\.n2015</u>vetustiori<neut><abl><sg><comp><irregadj>
<u>livymorph\.irrvetus66</u><u>lexent\.n2015</u>vetustiora<neut><nom><pl><comp><irregadj>
<u>livymorph\.irrvetus67</u><u>lexent\.n2015</u>vetustiorum<neut><gen><pl><comp><irregadj>
<u>livymorph\.irrvetus68</u><u>lexent\.n2015</u>vetustioribus<neut><dat><pl><comp><irregadj>
<u>livymorph\.irrvetus69</u><u>lexent\.n2015</u>vetustiora<neut><acc><pl><comp><irregadj>
<u>livymorph\.irrvetus70</u><u>lexent\.n2015</u>vetustioribus<neut><abl><pl><comp><irregadj>
<u>livymorph\.irrvetus71</u><u>lexent\.n2015</u>vetustius<neut><voc><sg><comp><irregadj>
<u>livymorph\.irrvetus72</u><u>lexent\.n2015</u>vetustiora<neut><voc><pl><comp><irregadj>
<u>livymorph\.irrvetus73</u><u>lexent\.n2015</u>veterrimus<masc><nom><sg><superl><irregadj>
<u>livymorph\.irrvetus74</u><u>lexent\.n2015</u>veterrimi<masc><gen><sg><superl><irregadj>
<u>livymorph\.irrvetus75</u><u>lexent\.n2015</u>veterrimo<masc><dat><sg><superl><irregadj>
<u>livymorph\.irrvetus76</u><u>lexent\.n2015</u>veterrimum<masc><acc><sg><superl><irregadj>
<u>livymorph\.irrvetus77</u><u>lexent\.n2015</u>veterrimo<masc><abl><sg><superl><irregadj>
<u>livymorph\.irrvetus78</u><u>lexent\.n2015</u>veterrimi<masc><nom><pl><superl><irregadj>
<u>livymorph\.irrvetus79</u><u>lexent\.n2015</u>veterrimorum<masc><gen><pl><superl><irregadj>
<u>livymorph\.irrvetus80</u><u>lexent\.n2015</u>veterrimis<masc><dat><pl><superl><irregadj>
<u>livymorph\.irrvetus81</u><u>lexent\.n2015</u>veterrimos<masc><acc><pl><superl><irregadj>
<u>livymorph\.irrvetus82</u><u>lexent\.n2015</u>veterrimis<masc><abl><pl><superl><irregadj>
<u>livymorph\.irrvetus83</u><u>lexent\.n2015</u>veterrime<masc><voc><sg><superl><irregadj>
<u>livymorph\.irrvetus84</u><u>lexent\.n2015</u>veterrimi<masc><voc><pl><superl><irregadj>
<u>livymorph\.irrvetus85</u><u>lexent\.n2015</u>veterrima<fem><nom><sg><superl><irregadj>
<u>livymorph\.irrvetus86</u><u>lexent\.n2015</u>veterrimae<fem><gen><sg><superl><irregadj>
<u>livymorph\.irrvetus87</u><u>lexent\.n2015</u>veterrimae<fem><dat><sg><superl><irregadj>
<u>livymorph\.irrvetus88</u><u>lexent\.n2015</u>veterrimam<fem><acc><sg><superl><irregadj>
<u>livymorph\.irrvetus89</u><u>lexent\.n2015</u>veterrima<fem><abl><sg><superl><irregadj>
<u>livymorph\.irrvetus90</u><u>lexent\.n2015</u>veterrimae<fem><nom><pl><superl><irregadj>
<u>livymorph\.irrvetus91</u><u>lexent\.n2015</u>veterrimarum<fem><gen><pl><superl><irregadj>
<u>livymorph\.irrvetus92</u><u>lexent\.n2015</u>veterrimis<fem><dat><pl><superl><irregadj>
<u>livymorph\.irrvetus93</u><u>lexent\.n2015</u>veterrimas<fem><acc><pl><superl><irregadj>
<u>livymorph\.irrvetus94</u><u>lexent\.n2015</u>veterrimis<fem><abl><pl><superl><irregadj>
<u>livymorph\.irrvetus95</u><u>lexent\.n2015</u>veterrima<fem><voc><sg><superl><irregadj>
<u>livymorph\.irrvetus96</u><u>lexent\.n2015</u>veterrimae<fem><voc><pl><superl><irregadj>
<u>livymorph\.irrvetus97</u><u>lexent\.n2015</u>veterrimum<neut><nom><sg><superl><irregadj>
<u>livymorph\.irrvetus98</u><u>lexent\.n2015</u>veterrimi<neut><gen><sg><superl><irregadj>
<u>livymorph\.irrvetus99</u><u>lexent\.n2015</u>veterrimo<neut><dat><sg><superl><irregadj>
<u>livymorph\.irrvetus100</u><u>lexent\.n2015</u>veterrimum<neut><acc><sg><superl><irregadj>
<u>livymorph\.irrvetus101</u><u>lexent\.n2015</u>veterrimo<neut><abl><sg><superl><irregadj>
<u>livymorph\.irrvetus102</u><u>lexent\.n2015</u>veterrima<neut><nom><pl><superl><irregadj>
<u>livymorph\.irrvetus103</u><u>lexent\.n2015</u>veterrimorum<neut><gen><pl><superl><irregadj>
<u>livymorph\.irrvetus104</u><u>lexent\.n2015</u>veterrimis<neut><dat><pl><superl><irregadj>
<u>livymorph\.irrvetus105</u><u>lexent\.n2015</u>veterrima<neut><acc><pl><superl><irregadj>
<u>livymorph\.irrvetus106</u><u>lexent\.n2015</u>veterrimis<neut><abl><pl><superl><irregadj>
<u>livymorph\.irrvetus107</u><u>lexent\.n2015</u>veterrimum<neut><voc><sg><superl><irregadj>
<u>livymorph\.irrvetus108</u><u>lexent\.n2015</u>veterrima<neut><voc><pl><superl><irregadj>
