/data/repos/latin/tabulae/test_build/parsers/minimum/latin.a: /data/repos/latin/tabulae/test_build/parsers/minimum/symbols.fst /data/repos/latin/tabulae/test_build/parsers/minimum/symbols/phonology.fst /data/repos/latin/tabulae/test_build/parsers/minimum/inflection.a /data/repos/latin/tabulae/test_build/parsers/minimum/acceptor.a 
/data/repos/latin/tabulae/test_build/parsers/minimum/verb.a: 

/data/repos/latin/tabulae/test_build/parsers/minimum/acceptor.a: /data/repos/latin/tabulae/test_build/parsers/minimum/verb.a

/data/repos/latin/tabulae/test_build/parsers/minimum/acceptors/verbstems.a: 
%.a: %.fst
	/usr/local/bin/fst-compiler $< $@
