<u>plinymorph\.irrgdv\_fero1</u><u>lexent\.n17964</u>ferendus<masc><nom><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero2</u><u>lexent\.n17964</u>ferendi<masc><gen><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero3</u><u>lexent\.n17964</u>ferendo<masc><dat><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero4</u><u>lexent\.n17964</u>ferendum<masc><acc><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero5</u><u>lexent\.n17964</u>ferendo<masc><abl><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero6</u><u>lexent\.n17964</u>ferendi<masc><nom><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero7</u><u>lexent\.n17964</u>ferendorum<masc><gen><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero8</u><u>lexent\.n17964</u>ferendis<masc><dat><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero9</u><u>lexent\.n17964</u>ferendos<masc><acc><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero10</u><u>lexent\.n17964</u>ferendis<masc><abl><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero11</u><u>lexent\.n17964</u>ferende<masc><voc><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero12</u><u>lexent\.n17964</u>ferendi<masc><voc><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero13</u><u>lexent\.n17964</u>ferenda<fem><nom><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero14</u><u>lexent\.n17964</u>ferendae<fem><gen><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero15</u><u>lexent\.n17964</u>ferendae<fem><dat><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero16</u><u>lexent\.n17964</u>ferendam<fem><acc><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero17</u><u>lexent\.n17964</u>ferenda<fem><abl><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero18</u><u>lexent\.n17964</u>ferendae<fem><nom><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero19</u><u>lexent\.n17964</u>ferendarum<fem><gen><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero20</u><u>lexent\.n17964</u>ferendis<fem><dat><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero21</u><u>lexent\.n17964</u>ferendas<fem><acc><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero22</u><u>lexent\.n17964</u>ferendis<fem><abl><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero23</u><u>lexent\.n17964</u>ferenda<fem><voc><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero24</u><u>lexent\.n17964</u>ferendae<fem><voc><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero25</u><u>lexent\.n17964</u>ferendum<neut><nom><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero26</u><u>lexent\.n17964</u>ferendi<neut><gen><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero27</u><u>lexent\.n17964</u>ferendo<neut><dat><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero28</u><u>lexent\.n17964</u>ferendum<neut><acc><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero29</u><u>lexent\.n17964</u>ferendo<neut><abl><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero30</u><u>lexent\.n17964</u>ferenda<neut><nom><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero31</u><u>lexent\.n17964</u>ferendorum<neut><gen><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero32</u><u>lexent\.n17964</u>ferendis<neut><dat><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero33</u><u>lexent\.n17964</u>ferenda<neut><acc><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero34</u><u>lexent\.n17964</u>ferendis<neut><abl><pl><irreggrndv>
<u>plinymorph\.irrgdv\_fero35</u><u>lexent\.n17964</u>ferendum<neut><voc><sg><irreggrndv>
<u>plinymorph\.irrgdv\_fero36</u><u>lexent\.n17964</u>ferenda<neut><voc><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo1</u><u>lexent\.n48771</u>ineundus<masc><nom><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo2</u><u>lexent\.n48771</u>ineundi<masc><gen><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo3</u><u>lexent\.n48771</u>ineundo<masc><dat><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo4</u><u>lexent\.n48771</u>ineundum<masc><acc><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo5</u><u>lexent\.n48771</u>ineundo<masc><abl><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo6</u><u>lexent\.n48771</u>ineundi<masc><nom><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo7</u><u>lexent\.n48771</u>ineundorum<masc><gen><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo8</u><u>lexent\.n48771</u>ineundis<masc><dat><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo9</u><u>lexent\.n48771</u>ineundos<masc><acc><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo10</u><u>lexent\.n48771</u>ineundis<masc><abl><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo11</u><u>lexent\.n48771</u>ineunde<masc><voc><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo12</u><u>lexent\.n48771</u>ineundi<masc><voc><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo13</u><u>lexent\.n48771</u>ineunda<fem><nom><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo14</u><u>lexent\.n48771</u>ineundae<fem><gen><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo15</u><u>lexent\.n48771</u>ineundae<fem><dat><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo16</u><u>lexent\.n48771</u>ineundam<fem><acc><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo17</u><u>lexent\.n48771</u>ineunda<fem><abl><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo18</u><u>lexent\.n48771</u>ineundae<fem><nom><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo19</u><u>lexent\.n48771</u>ineundarum<fem><gen><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo20</u><u>lexent\.n48771</u>ineundis<fem><dat><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo21</u><u>lexent\.n48771</u>ineundas<fem><acc><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo22</u><u>lexent\.n48771</u>ineundis<fem><abl><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo23</u><u>lexent\.n48771</u>ineunda<fem><voc><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo24</u><u>lexent\.n48771</u>ineundae<fem><voc><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo25</u><u>lexent\.n48771</u>ineundum<neut><nom><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo26</u><u>lexent\.n48771</u>ineundi<neut><gen><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo27</u><u>lexent\.n48771</u>ineundo<neut><dat><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo28</u><u>lexent\.n48771</u>ineundum<neut><acc><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo29</u><u>lexent\.n48771</u>ineundo<neut><abl><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo30</u><u>lexent\.n48771</u>ineunda<neut><nom><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo31</u><u>lexent\.n48771</u>ineundorum<neut><gen><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo32</u><u>lexent\.n48771</u>ineundis<neut><dat><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo33</u><u>lexent\.n48771</u>ineunda<neut><acc><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo34</u><u>lexent\.n48771</u>ineundis<neut><abl><pl><irreggrndv>
<u>plinymorph\.irrgdv\_ineo35</u><u>lexent\.n48771</u>ineundum<neut><voc><sg><irreggrndv>
<u>plinymorph\.irrgdv\_ineo36</u><u>lexent\.n48771</u>ineunda<neut><voc><pl><irreggrndv>
