$Gerundiveinfl$ =  <c1pres><gerundive>andus<masc><nom><sg><u>gdv\.c1pres\_1</u> |\
 <c1pres><gerundive>andi<masc><gen><sg><u>gdv\.c1pres\_2</u> |\
 <c1pres><gerundive>ando<masc><dat><sg><u>gdv\.c1pres\_3</u> |\
 <c1pres><gerundive>andum<masc><acc><sg><u>gdv\.c1pres\_4</u> |\
 <c1pres><gerundive>ando<masc><abl><sg><u>gdv\.c1pres\_5</u> |\
 <c1pres><gerundive>andi<masc><nom><pl><u>gdv\.c1pres\_6</u> |\
 <c1pres><gerundive>andorum<masc><gen><pl><u>gdv\.c1pres\_7</u> |\
 <c1pres><gerundive>andis<masc><dat><pl><u>gdv\.c1pres\_8</u> |\
 <c1pres><gerundive>andos<masc><acc><pl><u>gdv\.c1pres\_9</u> |\
 <c1pres><gerundive>andis<masc><abl><pl><u>gdv\.c1pres\_10</u> |\
 <c1pres><gerundive>ande<masc><nom><sg><u>gdv\.c1pres\_11</u> |\
 <c1pres><gerundive>andi<masc><nom><pl><u>gdv\.c1pres\_12</u> |\
 <c1pres><gerundive>anda<fem><nom><sg><u>gdv\.c1pres\_13</u> |\
 <c1pres><gerundive>andae<fem><gen><sg><u>gdv\.c1pres\_14</u> |\
 <c1pres><gerundive>andae<fem><dat><sg><u>gdv\.c1pres\_15</u> |\
 <c1pres><gerundive>andam<fem><acc><sg><u>gdv\.c1pres\_16</u> |\
 <c1pres><gerundive>anda<fem><abl><sg><u>gdv\.c1pres\_17</u> |\
 <c1pres><gerundive>andae<fem><nom><pl><u>gdv\.c1pres\_18</u> |\
 <c1pres><gerundive>andarum<fem><gen><pl><u>gdv\.c1pres\_19</u> |\
 <c1pres><gerundive>andis<fem><dat><pl><u>gdv\.c1pres\_20</u> |\
 <c1pres><gerundive>andas<fem><acc><pl><u>gdv\.c1pres\_21</u> |\
 <c1pres><gerundive>andis<fem><abl><pl><u>gdv\.c1pres\_22</u> |\
 <c1pres><gerundive>anda<fem><nom><sg><u>gdv\.c1pres\_23</u> |\
 <c1pres><gerundive>andae<fem><nom><pl><u>gdv\.c1pres\_24</u> |\
 <c1pres><gerundive>andum<neut><nom><sg><u>gdv\.c1pres\_25</u> |\
 <c1pres><gerundive>andi<neut><gen><sg><u>gdv\.c1pres\_26</u> |\
 <c1pres><gerundive>ando<neut><dat><sg><u>gdv\.c1pres\_27</u> |\
 <c1pres><gerundive>andum<neut><acc><sg><u>gdv\.c1pres\_28</u> |\
 <c1pres><gerundive>ando<neut><abl><sg><u>gdv\.c1pres\_29</u> |\
 <c1pres><gerundive>anda<neut><nom><pl><u>gdv\.c1pres\_30</u> |\
 <c1pres><gerundive>andorum<neut><gen><pl><u>gdv\.c1pres\_31</u> |\
 <c1pres><gerundive>andis<neut><dat><pl><u>gdv\.c1pres\_32</u> |\
 <c1pres><gerundive>anda<neut><acc><pl><u>gdv\.c1pres\_33</u> |\
 <c1pres><gerundive>andis<neut><abl><pl><u>gdv\.c1pres\_34</u> |\
 <c1pres><gerundive>andum<neut><nom><sg><u>gdv\.c1pres\_35</u> |\
 <c1pres><gerundive>anda<neut><nom><pl><u>gdv\.c1pres\_36</u> |\
 <c2pres><gerundive>endus<masc><nom><sg><u>gdv\.c2pres\_1</u> |\
 <c2pres><gerundive>endi<masc><gen><sg><u>gdv\.c2pres\_2</u> |\
 <c2pres><gerundive>endo<masc><dat><sg><u>gdv\.c2pres\_3</u> |\
 <c2pres><gerundive>endum<masc><acc><sg><u>gdv\.c2pres\_4</u> |\
 <c2pres><gerundive>endo<masc><abl><sg><u>gdv\.c2pres\_5</u> |\
 <c2pres><gerundive>endi<masc><nom><pl><u>gdv\.c2pres\_6</u> |\
 <c2pres><gerundive>endorum<masc><gen><pl><u>gdv\.c2pres\_7</u> |\
 <c2pres><gerundive>endis<masc><dat><pl><u>gdv\.c2pres\_8</u> |\
 <c2pres><gerundive>endos<masc><acc><pl><u>gdv\.c2pres\_9</u> |\
 <c2pres><gerundive>endis<masc><abl><pl><u>gdv\.c2pres\_10</u> |\
 <c2pres><gerundive>ende<masc><nom><sg><u>gdv\.c2pres\_11</u> |\
 <c2pres><gerundive>endi<masc><nom><pl><u>gdv\.c2pres\_12</u> |\
 <c2pres><gerundive>enda<fem><nom><sg><u>gdv\.c2pres\_13</u> |\
 <c2pres><gerundive>endae<fem><gen><sg><u>gdv\.c2pres\_14</u> |\
 <c2pres><gerundive>endae<fem><dat><sg><u>gdv\.c2pres\_15</u> |\
 <c2pres><gerundive>endam<fem><acc><sg><u>gdv\.c2pres\_16</u> |\
 <c2pres><gerundive>enda<fem><abl><sg><u>gdv\.c2pres\_17</u> |\
 <c2pres><gerundive>endae<fem><nom><pl><u>gdv\.c2pres\_18</u> |\
 <c2pres><gerundive>endarum<fem><gen><pl><u>gdv\.c2pres\_19</u> |\
 <c2pres><gerundive>endis<fem><dat><pl><u>gdv\.c2pres\_20</u> |\
 <c2pres><gerundive>endas<fem><acc><pl><u>gdv\.c2pres\_21</u> |\
 <c2pres><gerundive>endis<fem><abl><pl><u>gdv\.c2pres\_22</u> |\
 <c2pres><gerundive>enda<fem><nom><sg><u>gdv\.c2pres\_23</u> |\
 <c2pres><gerundive>endae<fem><nom><pl><u>gdv\.c2pres\_24</u> |\
 <c2pres><gerundive>endum<neut><nom><sg><u>gdv\.c2pres\_25</u> |\
 <c2pres><gerundive>endi<neut><gen><sg><u>gdv\.c2pres\_26</u> |\
 <c2pres><gerundive>endo<neut><dat><sg><u>gdv\.c2pres\_27</u> |\
 <c2pres><gerundive>endum<neut><acc><sg><u>gdv\.c2pres\_28</u> |\
 <c2pres><gerundive>endo<neut><abl><sg><u>gdv\.c2pres\_29</u> |\
 <c2pres><gerundive>enda<neut><nom><pl><u>gdv\.c2pres\_30</u> |\
 <c2pres><gerundive>endorum<neut><gen><pl><u>gdv\.c2pres\_31</u> |\
 <c2pres><gerundive>endis<neut><dat><pl><u>gdv\.c2pres\_32</u> |\
 <c2pres><gerundive>enda<neut><acc><pl><u>gdv\.c2pres\_33</u> |\
 <c2pres><gerundive>endis<neut><abl><pl><u>gdv\.c2pres\_34</u> |\
 <c2pres><gerundive>endum<neut><nom><sg><u>gdv\.c2pres\_35</u> |\
 <c2pres><gerundive>enda<neut><nom><pl><u>gdv\.c2pres\_36</u> |\
 <c3iopres><gerundive>iendus<masc><nom><sg><u>gdv\.c3iopres\_1</u> |\
 <c3iopres><gerundive>iendi<masc><gen><sg><u>gdv\.c3iopres\_2</u> |\
 <c3iopres><gerundive>iendo<masc><dat><sg><u>gdv\.c3iopres\_3</u> |\
 <c3iopres><gerundive>iendum<masc><acc><sg><u>gdv\.c3iopres\_4</u> |\
 <c3iopres><gerundive>iendo<masc><abl><sg><u>gdv\.c3iopres\_5</u> |\
 <c3iopres><gerundive>iendi<masc><nom><pl><u>gdv\.c3iopres\_6</u> |\
 <c3iopres><gerundive>iendorum<masc><gen><pl><u>gdv\.c3iopres\_7</u> |\
 <c3iopres><gerundive>iendis<masc><dat><pl><u>gdv\.c3iopres\_8</u> |\
 <c3iopres><gerundive>iendos<masc><acc><pl><u>gdv\.c3iopres\_9</u> |\
 <c3iopres><gerundive>iendis<masc><abl><pl><u>gdv\.c3iopres\_10</u> |\
 <c3iopres><gerundive>iende<masc><nom><sg><u>gdv\.c3iopres\_11</u> |\
 <c3iopres><gerundive>iendi<masc><nom><pl><u>gdv\.c3iopres\_12</u> |\
 <c3iopres><gerundive>ienda<fem><nom><sg><u>gdv\.c3iopres\_13</u> |\
 <c3iopres><gerundive>iendae<fem><gen><sg><u>gdv\.c3iopres\_14</u> |\
 <c3iopres><gerundive>iendae<fem><dat><sg><u>gdv\.c3iopres\_15</u> |\
 <c3iopres><gerundive>iendam<fem><acc><sg><u>gdv\.c3iopres\_16</u> |\
 <c3iopres><gerundive>ienda<fem><abl><sg><u>gdv\.c3iopres\_17</u> |\
 <c3iopres><gerundive>iendae<fem><nom><pl><u>gdv\.c3iopres\_18</u> |\
 <c3iopres><gerundive>iendarum<fem><gen><pl><u>gdv\.c3iopres\_19</u> |\
 <c3iopres><gerundive>iendis<fem><dat><pl><u>gdv\.c3iopres\_20</u> |\
 <c3iopres><gerundive>iendas<fem><acc><pl><u>gdv\.c3iopres\_21</u> |\
 <c3iopres><gerundive>iendis<fem><abl><pl><u>gdv\.c3iopres\_22</u> |\
 <c3iopres><gerundive>ienda<fem><nom><sg><u>gdv\.c3iopres\_23</u> |\
 <c3iopres><gerundive>iendae<fem><nom><pl><u>gdv\.c3iopres\_24</u> |\
 <c3iopres><gerundive>iendum<neut><nom><sg><u>gdv\.c3iopres\_25</u> |\
 <c3iopres><gerundive>iendi<neut><gen><sg><u>gdv\.c3iopres\_26</u> |\
 <c3iopres><gerundive>iendo<neut><dat><sg><u>gdv\.c3iopres\_27</u> |\
 <c3iopres><gerundive>iendum<neut><acc><sg><u>gdv\.c3iopres\_28</u> |\
 <c3iopres><gerundive>iendo<neut><abl><sg><u>gdv\.c3iopres\_29</u> |\
 <c3iopres><gerundive>ienda<neut><nom><pl><u>gdv\.c3iopres\_30</u> |\
 <c3iopres><gerundive>iendorum<neut><gen><pl><u>gdv\.c3iopres\_31</u> |\
 <c3iopres><gerundive>iendis<neut><dat><pl><u>gdv\.c3iopres\_32</u> |\
 <c3iopres><gerundive>ienda<neut><acc><pl><u>gdv\.c3iopres\_33</u> |\
 <c3iopres><gerundive>iendis<neut><abl><pl><u>gdv\.c3iopres\_34</u> |\
 <c3iopres><gerundive>iendum<neut><nom><sg><u>gdv\.c3iopres\_35</u> |\
 <c3iopres><gerundive>ienda<neut><nom><pl><u>gdv\.c3iopres\_36</u> |\
 <c3pres><gerundive>endus<masc><nom><sg><u>gdv\.c3pres\_1</u> |\
 <c3pres><gerundive>endi<masc><gen><sg><u>gdv\.c3pres\_2</u> |\
 <c3pres><gerundive>endo<masc><dat><sg><u>gdv\.c3pres\_3</u> |\
 <c3pres><gerundive>endum<masc><acc><sg><u>gdv\.c3pres\_4</u> |\
 <c3pres><gerundive>endo<masc><abl><sg><u>gdv\.c3pres\_5</u> |\
 <c3pres><gerundive>endi<masc><nom><pl><u>gdv\.c3pres\_6</u> |\
 <c3pres><gerundive>endorum<masc><gen><pl><u>gdv\.c3pres\_7</u> |\
 <c3pres><gerundive>endis<masc><dat><pl><u>gdv\.c3pres\_8</u> |\
 <c3pres><gerundive>endos<masc><acc><pl><u>gdv\.c3pres\_9</u> |\
 <c3pres><gerundive>endis<masc><abl><pl><u>gdv\.c3pres\_10</u> |\
 <c3pres><gerundive>ende<masc><nom><sg><u>gdv\.c3pres\_11</u> |\
 <c3pres><gerundive>endi<masc><nom><pl><u>gdv\.c3pres\_12</u> |\
 <c3pres><gerundive>enda<fem><nom><sg><u>gdv\.c3pres\_13</u> |\
 <c3pres><gerundive>endae<fem><gen><sg><u>gdv\.c3pres\_14</u> |\
 <c3pres><gerundive>endae<fem><dat><sg><u>gdv\.c3pres\_15</u> |\
 <c3pres><gerundive>endam<fem><acc><sg><u>gdv\.c3pres\_16</u> |\
 <c3pres><gerundive>enda<fem><abl><sg><u>gdv\.c3pres\_17</u> |\
 <c3pres><gerundive>endae<fem><nom><pl><u>gdv\.c3pres\_18</u> |\
 <c3pres><gerundive>endarum<fem><gen><pl><u>gdv\.c3pres\_19</u> |\
 <c3pres><gerundive>endis<fem><dat><pl><u>gdv\.c3pres\_20</u> |\
 <c3pres><gerundive>endas<fem><acc><pl><u>gdv\.c3pres\_21</u> |\
 <c3pres><gerundive>endis<fem><abl><pl><u>gdv\.c3pres\_22</u> |\
 <c3pres><gerundive>enda<fem><nom><sg><u>gdv\.c3pres\_23</u> |\
 <c3pres><gerundive>endae<fem><nom><pl><u>gdv\.c3pres\_24</u> |\
 <c3pres><gerundive>endum<neut><nom><sg><u>gdv\.c3pres\_25</u> |\
 <c3pres><gerundive>endi<neut><gen><sg><u>gdv\.c3pres\_26</u> |\
 <c3pres><gerundive>endo<neut><dat><sg><u>gdv\.c3pres\_27</u> |\
 <c3pres><gerundive>endum<neut><acc><sg><u>gdv\.c3pres\_28</u> |\
 <c3pres><gerundive>endo<neut><abl><sg><u>gdv\.c3pres\_29</u> |\
 <c3pres><gerundive>enda<neut><nom><pl><u>gdv\.c3pres\_30</u> |\
 <c3pres><gerundive>endorum<neut><gen><pl><u>gdv\.c3pres\_31</u> |\
 <c3pres><gerundive>endis<neut><dat><pl><u>gdv\.c3pres\_32</u> |\
 <c3pres><gerundive>enda<neut><acc><pl><u>gdv\.c3pres\_33</u> |\
 <c3pres><gerundive>endis<neut><abl><pl><u>gdv\.c3pres\_34</u> |\
 <c3pres><gerundive>endum<neut><nom><sg><u>gdv\.c3pres\_35</u> |\
 <c3pres><gerundive>enda<neut><nom><pl><u>gdv\.c3pres\_36</u> |\
 <c4pres><gerundive>iendus<masc><nom><sg><u>gdv\.c4pres\_1</u> |\
 <c4pres><gerundive>iendi<masc><gen><sg><u>gdv\.c4pres\_2</u> |\
 <c4pres><gerundive>iendo<masc><dat><sg><u>gdv\.c4pres\_3</u> |\
 <c4pres><gerundive>iendum<masc><acc><sg><u>gdv\.c4pres\_4</u> |\
 <c4pres><gerundive>iendo<masc><abl><sg><u>gdv\.c4pres\_5</u> |\
 <c4pres><gerundive>iendi<masc><nom><pl><u>gdv\.c4pres\_6</u> |\
 <c4pres><gerundive>iendorum<masc><gen><pl><u>gdv\.c4pres\_7</u> |\
 <c4pres><gerundive>iendis<masc><dat><pl><u>gdv\.c4pres\_8</u> |\
 <c4pres><gerundive>iendos<masc><acc><pl><u>gdv\.c4pres\_9</u> |\
 <c4pres><gerundive>iendis<masc><abl><pl><u>gdv\.c4pres\_10</u> |\
 <c4pres><gerundive>iende<masc><nom><sg><u>gdv\.c4pres\_11</u> |\
 <c4pres><gerundive>iendi<masc><nom><pl><u>gdv\.c4pres\_12</u> |\
 <c4pres><gerundive>ienda<fem><nom><sg><u>gdv\.c4pres\_13</u> |\
 <c4pres><gerundive>iendae<fem><gen><sg><u>gdv\.c4pres\_14</u> |\
 <c4pres><gerundive>iendae<fem><dat><sg><u>gdv\.c4pres\_15</u> |\
 <c4pres><gerundive>iendam<fem><acc><sg><u>gdv\.c4pres\_16</u> |\
 <c4pres><gerundive>ienda<fem><abl><sg><u>gdv\.c4pres\_17</u> |\
 <c4pres><gerundive>iendae<fem><nom><pl><u>gdv\.c4pres\_18</u> |\
 <c4pres><gerundive>iendarum<fem><gen><pl><u>gdv\.c4pres\_19</u> |\
 <c4pres><gerundive>iendis<fem><dat><pl><u>gdv\.c4pres\_20</u> |\
 <c4pres><gerundive>iendas<fem><acc><pl><u>gdv\.c4pres\_21</u> |\
 <c4pres><gerundive>iendis<fem><abl><pl><u>gdv\.c4pres\_22</u> |\
 <c4pres><gerundive>ienda<fem><nom><sg><u>gdv\.c4pres\_23</u> |\
 <c4pres><gerundive>iendae<fem><nom><pl><u>gdv\.c4pres\_24</u> |\
 <c4pres><gerundive>iendum<neut><nom><sg><u>gdv\.c4pres\_25</u> |\
 <c4pres><gerundive>iendi<neut><gen><sg><u>gdv\.c4pres\_26</u> |\
 <c4pres><gerundive>iendo<neut><dat><sg><u>gdv\.c4pres\_27</u> |\
 <c4pres><gerundive>iendum<neut><acc><sg><u>gdv\.c4pres\_28</u> |\
 <c4pres><gerundive>iendo<neut><abl><sg><u>gdv\.c4pres\_29</u> |\
 <c4pres><gerundive>ienda<neut><nom><pl><u>gdv\.c4pres\_30</u> |\
 <c4pres><gerundive>iendorum<neut><gen><pl><u>gdv\.c4pres\_31</u> |\
 <c4pres><gerundive>iendis<neut><dat><pl><u>gdv\.c4pres\_32</u> |\
 <c4pres><gerundive>ienda<neut><acc><pl><u>gdv\.c4pres\_33</u> |\
 <c4pres><gerundive>iendis<neut><abl><pl><u>gdv\.c4pres\_34</u> |\
 <c4pres><gerundive>iendum<neut><nom><sg><u>gdv\.c4pres\_35</u> |\
 <c4pres><gerundive>ienda<neut><nom><pl><u>gdv\.c4pres\_36</u> |\
 <conj1><gerundive>andus<masc><nom><sg><u>gdv\.conj1\_1</u> |\
 <conj1><gerundive>andi<masc><gen><sg><u>gdv\.conj1\_2</u> |\
 <conj1><gerundive>ando<masc><dat><sg><u>gdv\.conj1\_3</u> |\
 <conj1><gerundive>andum<masc><acc><sg><u>gdv\.conj1\_4</u> |\
 <conj1><gerundive>ando<masc><abl><sg><u>gdv\.conj1\_5</u> |\
 <conj1><gerundive>andi<masc><nom><pl><u>gdv\.conj1\_6</u> |\
 <conj1><gerundive>andorum<masc><gen><pl><u>gdv\.conj1\_7</u> |\
 <conj1><gerundive>andis<masc><dat><pl><u>gdv\.conj1\_8</u> |\
 <conj1><gerundive>andos<masc><acc><pl><u>gdv\.conj1\_9</u> |\
 <conj1><gerundive>andis<masc><abl><pl><u>gdv\.conj1\_10</u> |\
 <conj1><gerundive>ande<masc><nom><sg><u>gdv\.conj1\_11</u> |\
 <conj1><gerundive>andi<masc><nom><pl><u>gdv\.conj1\_12</u> |\
 <conj1><gerundive>anda<fem><nom><sg><u>gdv\.conj1\_13</u> |\
 <conj1><gerundive>andae<fem><gen><sg><u>gdv\.conj1\_14</u> |\
 <conj1><gerundive>andae<fem><dat><sg><u>gdv\.conj1\_15</u> |\
 <conj1><gerundive>andam<fem><acc><sg><u>gdv\.conj1\_16</u> |\
 <conj1><gerundive>anda<fem><abl><sg><u>gdv\.conj1\_17</u> |\
 <conj1><gerundive>andae<fem><nom><pl><u>gdv\.conj1\_18</u> |\
 <conj1><gerundive>andarum<fem><gen><pl><u>gdv\.conj1\_19</u> |\
 <conj1><gerundive>andis<fem><dat><pl><u>gdv\.conj1\_20</u> |\
 <conj1><gerundive>andas<fem><acc><pl><u>gdv\.conj1\_21</u> |\
 <conj1><gerundive>andis<fem><abl><pl><u>gdv\.conj1\_22</u> |\
 <conj1><gerundive>anda<fem><nom><sg><u>gdv\.conj1\_23</u> |\
 <conj1><gerundive>andae<fem><nom><pl><u>gdv\.conj1\_24</u> |\
 <conj1><gerundive>andum<neut><nom><sg><u>gdv\.conj1\_25</u> |\
 <conj1><gerundive>andi<neut><gen><sg><u>gdv\.conj1\_26</u> |\
 <conj1><gerundive>ando<neut><dat><sg><u>gdv\.conj1\_27</u> |\
 <conj1><gerundive>andum<neut><acc><sg><u>gdv\.conj1\_28</u> |\
 <conj1><gerundive>ando<neut><abl><sg><u>gdv\.conj1\_29</u> |\
 <conj1><gerundive>anda<neut><nom><pl><u>gdv\.conj1\_30</u> |\
 <conj1><gerundive>andorum<neut><gen><pl><u>gdv\.conj1\_31</u> |\
 <conj1><gerundive>andis<neut><dat><pl><u>gdv\.conj1\_32</u> |\
 <conj1><gerundive>anda<neut><acc><pl><u>gdv\.conj1\_33</u> |\
 <conj1><gerundive>andis<neut><abl><pl><u>gdv\.conj1\_34</u> |\
 <conj1><gerundive>andum<neut><nom><sg><u>gdv\.conj1\_35</u> |\
 <conj1><gerundive>anda<neut><nom><pl><u>gdv\.conj1\_36</u> |\
 <conj2><gerundive>endus<masc><nom><sg><u>gdv\.conj2\_1</u> |\
 <conj2><gerundive>endi<masc><gen><sg><u>gdv\.conj2\_2</u> |\
 <conj2><gerundive>endo<masc><dat><sg><u>gdv\.conj2\_3</u> |\
 <conj2><gerundive>endum<masc><acc><sg><u>gdv\.conj2\_4</u> |\
 <conj2><gerundive>endo<masc><abl><sg><u>gdv\.conj2\_5</u> |\
 <conj2><gerundive>endi<masc><nom><pl><u>gdv\.conj2\_6</u> |\
 <conj2><gerundive>endorum<masc><gen><pl><u>gdv\.conj2\_7</u> |\
 <conj2><gerundive>endis<masc><dat><pl><u>gdv\.conj2\_8</u> |\
 <conj2><gerundive>endos<masc><acc><pl><u>gdv\.conj2\_9</u> |\
 <conj2><gerundive>endis<masc><abl><pl><u>gdv\.conj2\_10</u> |\
 <conj2><gerundive>ende<masc><nom><sg><u>gdv\.conj2\_11</u> |\
 <conj2><gerundive>endi<masc><nom><pl><u>gdv\.conj2\_12</u> |\
 <conj2><gerundive>enda<fem><nom><sg><u>gdv\.conj2\_13</u> |\
 <conj2><gerundive>endae<fem><gen><sg><u>gdv\.conj2\_14</u> |\
 <conj2><gerundive>endae<fem><dat><sg><u>gdv\.conj2\_15</u> |\
 <conj2><gerundive>endam<fem><acc><sg><u>gdv\.conj2\_16</u> |\
 <conj2><gerundive>enda<fem><abl><sg><u>gdv\.conj2\_17</u> |\
 <conj2><gerundive>endae<fem><nom><pl><u>gdv\.conj2\_18</u> |\
 <conj2><gerundive>endarum<fem><gen><pl><u>gdv\.conj2\_19</u> |\
 <conj2><gerundive>endis<fem><dat><pl><u>gdv\.conj2\_20</u> |\
 <conj2><gerundive>endas<fem><acc><pl><u>gdv\.conj2\_21</u> |\
 <conj2><gerundive>endis<fem><abl><pl><u>gdv\.conj2\_22</u> |\
 <conj2><gerundive>enda<fem><nom><sg><u>gdv\.conj2\_23</u> |\
 <conj2><gerundive>endae<fem><nom><pl><u>gdv\.conj2\_24</u> |\
 <conj2><gerundive>endum<neut><nom><sg><u>gdv\.conj2\_25</u> |\
 <conj2><gerundive>endi<neut><gen><sg><u>gdv\.conj2\_26</u> |\
 <conj2><gerundive>endo<neut><dat><sg><u>gdv\.conj2\_27</u> |\
 <conj2><gerundive>endum<neut><acc><sg><u>gdv\.conj2\_28</u> |\
 <conj2><gerundive>endo<neut><abl><sg><u>gdv\.conj2\_29</u> |\
 <conj2><gerundive>enda<neut><nom><pl><u>gdv\.conj2\_30</u> |\
 <conj2><gerundive>endorum<neut><gen><pl><u>gdv\.conj2\_31</u> |\
 <conj2><gerundive>endis<neut><dat><pl><u>gdv\.conj2\_32</u> |\
 <conj2><gerundive>enda<neut><acc><pl><u>gdv\.conj2\_33</u> |\
 <conj2><gerundive>endis<neut><abl><pl><u>gdv\.conj2\_34</u> |\
 <conj2><gerundive>endum<neut><nom><sg><u>gdv\.conj2\_35</u> |\
 <conj2><gerundive>enda<neut><nom><pl><u>gdv\.conj2\_36</u> |\
 <conj3><gerundive>endus<masc><nom><sg><u>gdv\.conj3\_1</u> |\
 <conj3><gerundive>endi<masc><gen><sg><u>gdv\.conj3\_2</u> |\
 <conj3><gerundive>endo<masc><dat><sg><u>gdv\.conj3\_3</u> |\
 <conj3><gerundive>endum<masc><acc><sg><u>gdv\.conj3\_4</u> |\
 <conj3><gerundive>endo<masc><abl><sg><u>gdv\.conj3\_5</u> |\
 <conj3><gerundive>endi<masc><nom><pl><u>gdv\.conj3\_6</u> |\
 <conj3><gerundive>endorum<masc><gen><pl><u>gdv\.conj3\_7</u> |\
 <conj3><gerundive>endis<masc><dat><pl><u>gdv\.conj3\_8</u> |\
 <conj3><gerundive>endos<masc><acc><pl><u>gdv\.conj3\_9</u> |\
 <conj3><gerundive>endis<masc><abl><pl><u>gdv\.conj3\_10</u> |\
 <conj3><gerundive>ende<masc><nom><sg><u>gdv\.conj3\_11</u> |\
 <conj3><gerundive>endi<masc><nom><pl><u>gdv\.conj3\_12</u> |\
 <conj3><gerundive>enda<fem><nom><sg><u>gdv\.conj3\_13</u> |\
 <conj3><gerundive>endae<fem><gen><sg><u>gdv\.conj3\_14</u> |\
 <conj3><gerundive>endae<fem><dat><sg><u>gdv\.conj3\_15</u> |\
 <conj3><gerundive>endam<fem><acc><sg><u>gdv\.conj3\_16</u> |\
 <conj3><gerundive>enda<fem><abl><sg><u>gdv\.conj3\_17</u> |\
 <conj3><gerundive>endae<fem><nom><pl><u>gdv\.conj3\_18</u> |\
 <conj3><gerundive>endarum<fem><gen><pl><u>gdv\.conj3\_19</u> |\
 <conj3><gerundive>endis<fem><dat><pl><u>gdv\.conj3\_20</u> |\
 <conj3><gerundive>endas<fem><acc><pl><u>gdv\.conj3\_21</u> |\
 <conj3><gerundive>endis<fem><abl><pl><u>gdv\.conj3\_22</u> |\
 <conj3><gerundive>enda<fem><nom><sg><u>gdv\.conj3\_23</u> |\
 <conj3><gerundive>endae<fem><nom><pl><u>gdv\.conj3\_24</u> |\
 <conj3><gerundive>endum<neut><nom><sg><u>gdv\.conj3\_25</u> |\
 <conj3><gerundive>endi<neut><gen><sg><u>gdv\.conj3\_26</u> |\
 <conj3><gerundive>endo<neut><dat><sg><u>gdv\.conj3\_27</u> |\
 <conj3><gerundive>endum<neut><acc><sg><u>gdv\.conj3\_28</u> |\
 <conj3><gerundive>endo<neut><abl><sg><u>gdv\.conj3\_29</u> |\
 <conj3><gerundive>enda<neut><nom><pl><u>gdv\.conj3\_30</u> |\
 <conj3><gerundive>endorum<neut><gen><pl><u>gdv\.conj3\_31</u> |\
 <conj3><gerundive>endis<neut><dat><pl><u>gdv\.conj3\_32</u> |\
 <conj3><gerundive>enda<neut><acc><pl><u>gdv\.conj3\_33</u> |\
 <conj3><gerundive>endis<neut><abl><pl><u>gdv\.conj3\_34</u> |\
 <conj3><gerundive>endum<neut><nom><sg><u>gdv\.conj3\_35</u> |\
 <conj3><gerundive>enda<neut><nom><pl><u>gdv\.conj3\_36</u> |\
 <conj3io><gerundive>iendus<masc><nom><sg><u>gdv\.conj3io\_1</u> |\
 <conj3io><gerundive>iendi<masc><gen><sg><u>gdv\.conj3io\_2</u> |\
 <conj3io><gerundive>iendo<masc><dat><sg><u>gdv\.conj3io\_3</u> |\
 <conj3io><gerundive>iendum<masc><acc><sg><u>gdv\.conj3io\_4</u> |\
 <conj3io><gerundive>iendo<masc><abl><sg><u>gdv\.conj3io\_5</u> |\
 <conj3io><gerundive>iendi<masc><nom><pl><u>gdv\.conj3io\_6</u> |\
 <conj3io><gerundive>iendorum<masc><gen><pl><u>gdv\.conj3io\_7</u> |\
 <conj3io><gerundive>iendis<masc><dat><pl><u>gdv\.conj3io\_8</u> |\
 <conj3io><gerundive>iendos<masc><acc><pl><u>gdv\.conj3io\_9</u> |\
 <conj3io><gerundive>iendis<masc><abl><pl><u>gdv\.conj3io\_10</u> |\
 <conj3io><gerundive>iende<masc><nom><sg><u>gdv\.conj3io\_11</u> |\
 <conj3io><gerundive>iendi<masc><nom><pl><u>gdv\.conj3io\_12</u> |\
 <conj3io><gerundive>ienda<fem><nom><sg><u>gdv\.conj3io\_13</u> |\
 <conj3io><gerundive>iendae<fem><gen><sg><u>gdv\.conj3io\_14</u> |\
 <conj3io><gerundive>iendae<fem><dat><sg><u>gdv\.conj3io\_15</u> |\
 <conj3io><gerundive>iendam<fem><acc><sg><u>gdv\.conj3io\_16</u> |\
 <conj3io><gerundive>ienda<fem><abl><sg><u>gdv\.conj3io\_17</u> |\
 <conj3io><gerundive>iendae<fem><nom><pl><u>gdv\.conj3io\_18</u> |\
 <conj3io><gerundive>iendarum<fem><gen><pl><u>gdv\.conj3io\_19</u> |\
 <conj3io><gerundive>iendis<fem><dat><pl><u>gdv\.conj3io\_20</u> |\
 <conj3io><gerundive>iendas<fem><acc><pl><u>gdv\.conj3io\_21</u> |\
 <conj3io><gerundive>iendis<fem><abl><pl><u>gdv\.conj3io\_22</u> |\
 <conj3io><gerundive>ienda<fem><nom><sg><u>gdv\.conj3io\_23</u> |\
 <conj3io><gerundive>iendae<fem><nom><pl><u>gdv\.conj3io\_24</u> |\
 <conj3io><gerundive>iendum<neut><nom><sg><u>gdv\.conj3io\_25</u> |\
 <conj3io><gerundive>iendi<neut><gen><sg><u>gdv\.conj3io\_26</u> |\
 <conj3io><gerundive>iendo<neut><dat><sg><u>gdv\.conj3io\_27</u> |\
 <conj3io><gerundive>iendum<neut><acc><sg><u>gdv\.conj3io\_28</u> |\
 <conj3io><gerundive>iendo<neut><abl><sg><u>gdv\.conj3io\_29</u> |\
 <conj3io><gerundive>ienda<neut><nom><pl><u>gdv\.conj3io\_30</u> |\
 <conj3io><gerundive>iendorum<neut><gen><pl><u>gdv\.conj3io\_31</u> |\
 <conj3io><gerundive>iendis<neut><dat><pl><u>gdv\.conj3io\_32</u> |\
 <conj3io><gerundive>ienda<neut><acc><pl><u>gdv\.conj3io\_33</u> |\
 <conj3io><gerundive>iendis<neut><abl><pl><u>gdv\.conj3io\_34</u> |\
 <conj3io><gerundive>iendum<neut><nom><sg><u>gdv\.conj3io\_35</u> |\
 <conj3io><gerundive>ienda<neut><nom><pl><u>gdv\.conj3io\_36</u> |\
 <conj4><gerundive>iendus<masc><nom><sg><u>gdv\.conj4\_1</u> |\
 <conj4><gerundive>iendi<masc><gen><sg><u>gdv\.conj4\_2</u> |\
 <conj4><gerundive>iendo<masc><dat><sg><u>gdv\.conj4\_3</u> |\
 <conj4><gerundive>iendum<masc><acc><sg><u>gdv\.conj4\_4</u> |\
 <conj4><gerundive>iendo<masc><abl><sg><u>gdv\.conj4\_5</u> |\
 <conj4><gerundive>iendi<masc><nom><pl><u>gdv\.conj4\_6</u> |\
 <conj4><gerundive>iendorum<masc><gen><pl><u>gdv\.conj4\_7</u> |\
 <conj4><gerundive>iendis<masc><dat><pl><u>gdv\.conj4\_8</u> |\
 <conj4><gerundive>iendos<masc><acc><pl><u>gdv\.conj4\_9</u> |\
 <conj4><gerundive>iendis<masc><abl><pl><u>gdv\.conj4\_10</u> |\
 <conj4><gerundive>iende<masc><nom><sg><u>gdv\.conj4\_11</u> |\
 <conj4><gerundive>iendi<masc><nom><pl><u>gdv\.conj4\_12</u> |\
 <conj4><gerundive>ienda<fem><nom><sg><u>gdv\.conj4\_13</u> |\
 <conj4><gerundive>iendae<fem><gen><sg><u>gdv\.conj4\_14</u> |\
 <conj4><gerundive>iendae<fem><dat><sg><u>gdv\.conj4\_15</u> |\
 <conj4><gerundive>iendam<fem><acc><sg><u>gdv\.conj4\_16</u> |\
 <conj4><gerundive>ienda<fem><abl><sg><u>gdv\.conj4\_17</u> |\
 <conj4><gerundive>iendae<fem><nom><pl><u>gdv\.conj4\_18</u> |\
 <conj4><gerundive>iendarum<fem><gen><pl><u>gdv\.conj4\_19</u> |\
 <conj4><gerundive>iendis<fem><dat><pl><u>gdv\.conj4\_20</u> |\
 <conj4><gerundive>iendas<fem><acc><pl><u>gdv\.conj4\_21</u> |\
 <conj4><gerundive>iendis<fem><abl><pl><u>gdv\.conj4\_22</u> |\
 <conj4><gerundive>ienda<fem><nom><sg><u>gdv\.conj4\_23</u> |\
 <conj4><gerundive>iendae<fem><nom><pl><u>gdv\.conj4\_24</u> |\
 <conj4><gerundive>iendum<neut><nom><sg><u>gdv\.conj4\_25</u> |\
 <conj4><gerundive>iendi<neut><gen><sg><u>gdv\.conj4\_26</u> |\
 <conj4><gerundive>iendo<neut><dat><sg><u>gdv\.conj4\_27</u> |\
 <conj4><gerundive>iendum<neut><acc><sg><u>gdv\.conj4\_28</u> |\
 <conj4><gerundive>iendo<neut><abl><sg><u>gdv\.conj4\_29</u> |\
 <conj4><gerundive>ienda<neut><nom><pl><u>gdv\.conj4\_30</u> |\
 <conj4><gerundive>iendorum<neut><gen><pl><u>gdv\.conj4\_31</u> |\
 <conj4><gerundive>iendis<neut><dat><pl><u>gdv\.conj4\_32</u> |\
 <conj4><gerundive>ienda<neut><acc><pl><u>gdv\.conj4\_33</u> |\
 <conj4><gerundive>iendis<neut><abl><pl><u>gdv\.conj4\_34</u> |\
 <conj4><gerundive>iendum<neut><nom><sg><u>gdv\.conj4\_35</u> |\
 <conj4><gerundive>ienda<neut><nom><pl><u>gdv\.conj4\_36</u> |\
 <conj1><gerundive>andus<masc><nom><sg><u>gdv\.conj1\_1</u> |\
 <conj1><gerundive>andi<masc><gen><sg><u>gdv\.conj1\_2</u> |\
 <conj1><gerundive>ando<masc><dat><sg><u>gdv\.conj1\_3</u> |\
 <conj1><gerundive>andum<masc><acc><sg><u>gdv\.conj1\_4</u> |\
 <conj1><gerundive>ando<masc><abl><sg><u>gdv\.conj1\_5</u> |\
 <conj1><gerundive>andi<masc><nom><pl><u>gdv\.conj1\_6</u> |\
 <conj1><gerundive>andorum<masc><gen><pl><u>gdv\.conj1\_7</u> |\
 <conj1><gerundive>andis<masc><dat><pl><u>gdv\.conj1\_8</u> |\
 <conj1><gerundive>andos<masc><acc><pl><u>gdv\.conj1\_9</u> |\
 <conj1><gerundive>andis<masc><abl><pl><u>gdv\.conj1\_10</u> |\
 <conj1><gerundive>ande<masc><nom><sg><u>gdv\.conj1\_11</u> |\
 <conj1><gerundive>andi<masc><nom><pl><u>gdv\.conj1\_12</u> |\
 <conj1><gerundive>anda<fem><nom><sg><u>gdv\.conj1\_13</u> |\
 <conj1><gerundive>andae<fem><gen><sg><u>gdv\.conj1\_14</u> |\
 <conj1><gerundive>andae<fem><dat><sg><u>gdv\.conj1\_15</u> |\
 <conj1><gerundive>andam<fem><acc><sg><u>gdv\.conj1\_16</u> |\
 <conj1><gerundive>anda<fem><abl><sg><u>gdv\.conj1\_17</u> |\
 <conj1><gerundive>andae<fem><nom><pl><u>gdv\.conj1\_18</u> |\
 <conj1><gerundive>andarum<fem><gen><pl><u>gdv\.conj1\_19</u> |\
 <conj1><gerundive>andis<fem><dat><pl><u>gdv\.conj1\_20</u> |\
 <conj1><gerundive>andas<fem><acc><pl><u>gdv\.conj1\_21</u> |\
 <conj1><gerundive>andis<fem><abl><pl><u>gdv\.conj1\_22</u> |\
 <conj1><gerundive>anda<fem><nom><sg><u>gdv\.conj1\_23</u> |\
 <conj1><gerundive>andae<fem><nom><pl><u>gdv\.conj1\_24</u> |\
 <conj1><gerundive>andum<neut><nom><sg><u>gdv\.conj1\_25</u> |\
 <conj1><gerundive>andi<neut><gen><sg><u>gdv\.conj1\_26</u> |\
 <conj1><gerundive>ando<neut><dat><sg><u>gdv\.conj1\_27</u> |\
 <conj1><gerundive>andum<neut><acc><sg><u>gdv\.conj1\_28</u> |\
 <conj1><gerundive>ando<neut><abl><sg><u>gdv\.conj1\_29</u> |\
 <conj1><gerundive>anda<neut><nom><pl><u>gdv\.conj1\_30</u> |\
 <conj1><gerundive>andorum<neut><gen><pl><u>gdv\.conj1\_31</u> |\
 <conj1><gerundive>andis<neut><dat><pl><u>gdv\.conj1\_32</u> |\
 <conj1><gerundive>anda<neut><acc><pl><u>gdv\.conj1\_33</u> |\
 <conj1><gerundive>andis<neut><abl><pl><u>gdv\.conj1\_34</u> |\
 <conj1><gerundive>andum<neut><nom><sg><u>gdv\.conj1\_35</u> |\
 <conj1><gerundive>anda<neut><nom><pl><u>gdv\.conj1\_36</u>

$Gerundiveinfl$
