/Users/nsmith/Desktop/tabulae/jvm/src/test/resources/parsers/stress/one-each/latin.a: /Users/nsmith/Desktop/tabulae/jvm/src/test/resources/parsers/stress/one-each/symbols.fst /Users/nsmith/Desktop/tabulae/jvm/src/test/resources/parsers/stress/one-each/symbols/phonology.fst /Users/nsmith/Desktop/tabulae/jvm/src/test/resources/parsers/stress/one-each/inflection.a /Users/nsmith/Desktop/tabulae/jvm/src/test/resources/parsers/stress/one-each/acceptor.a 
%.a: %.fst
	/usr/local/bin/fst-compiler-utf8 $< $@
