<u>livymorph\.irrinf1</u><u>lexent\.n46529</u>esse<pres><act><irreginfin>
<u>livymorph\.irrinf2</u><u>lexent\.n46529</u>fuisse<pft><act><irreginfin>
<u>livymorph\.irrinf3</u><u>lexent\.n15156</u>esse<pres><act><irreginfin>
<u>livymorph\.irrinf4</u><u>lexent\.n15156</u>ire<pres><act><irreginfin>
<u>livymorph\.irrinf5</u><u>lexent\.n15156</u>isse<pft><act><irreginfin>
<u>livymorph\.irrinf6</u><u>lexent\.n15156</u>ivisse<pft><act><irreginfin>
<u>livymorph\.irrinf7</u><u>lexent\.n51298</u>velle<pres><act><irreginfin>
<u>livymorph\.irrinf8</u><u>lexent\.n51298</u>voluisse<pft><act><irreginfin>
<u>livymorph\.irrinf9</u><u>lexent\.n27761</u>malle<pres><act><irreginfin>
<u>livymorph\.irrinf10</u><u>lexent\.n27761</u>maluisse<pft><act><irreginfin>
<u>livymorph\.irrinf11</u><u>lexent\.n31124</u>nolle<pres><act><irreginfin>
<u>livymorph\.irrinf12</u><u>lexent\.n31124</u>noluisse<pft><act><irreginfin>
<u>livymorph\.irrinf13</u><u>lexent\.n18209</u>fieri<pres><act><irreginfin>
<u>livymorph\.irrinf14</u><u>lexent\.n8883</u>coepisse<pft><act><irreginfin>
<u>livymorph\.irrinf15</u><u>lexent\.n32256</u>odisse<pft><act><irreginfin>
<u>livymorph\.irrinf16</u><u>lexent\.n28593</u>meminisse<pft><act><irreginfin>
<u>livymorph\.irrinf17</u><u>lexent\.n18534</u>fari<pres><act><irreginfin>
<u>livymorph\.irrinf18</u><u>lexent\.n40074</u>quire<pres><act><irreginfin>
<u>livymorph\.irrinf19</u><u>lexent\.n40074</u>quisse<pft><act><irreginfin>
<u>livymorph\.irrinf20</u><u>lexent\.n33239</u>ovare<pres><act><irreginfin>
<u>livymorph\.irrinf21</u><u>lexent\.n26547</u>licere<pres><act><irreginfin>
<u>livymorph\.irrinf22</u><u>lexent\.n26547</u>licuisse<pft><act><irreginfin>
<u>livymorph\.irrinf23</u><u>lexent\.n37193</u>posse<pres><act><irreginfin>
<u>livymorph\.irrinf24</u><u>lexent\.n37193</u>potuisse<pft><act><irreginfin>
<u>livymorph\.irrinf25</u><u>lexent\.n15868</u>iri<pres><pass><irreginfin>
<u>livymorph\.irrinf25</u><u>lexent\.n31777</u>obrepisse<pft><act><irreginfin>
<u>livymorph\.irrinf26</u><u>lexent\.n65</u>abire<pres><act><irreginfin>
<u>livymorph\.irrinf27</u><u>lexent\.n65</u>abiri<pres><pass><irreginfin>
<u>livymorph\.irrinf27</u><u>lexent\.n46529</u>fore<fut><act><irreginfin>
<u>livymorph\.irrinf28</u><u>lexent\.n13860</u>differri<pres><pass><irreginfin>
<u>livymorph\.irrinf29</u><u>lexent\.n13860</u>differre<pres><act><irreginfin>
